### ISSUE TITLE
help

### ISSUE THREAD

**Issue by TeaqariaWTF** [nikhilbadyal/docker-py-revanced#110]
after last merge i totally get error 

![Screenshot_20221222-010031](https://user-images.githubusercontent.com/90970076/209010575-25203314-66ea-4d0c-b57b-a1f48b16e89a.png)

**Comment by nikhilbadyal** [comment]
Weird, Unable to  reproduce. Can you try once again and report back with logs of the GitHub Action.

**Comment by TeaqariaWTF** [comment]
how do i get the logs
@nikhilbadyal

**Comment by nikhilbadyal** [comment]
Just run it and share the browser url.

**Comment by TeaqariaWTF** [comment]
https://pipelines.actions.githubusercontent.com/serviceHosts/b94639b4-a22f-4ea1-86cc-459fe813b946/_apis/pipelines/1/runs/35/signedlogcontent/2?urlExpires=2022-12-22T04%3A33%3A16.0575266Z&urlSigningMethod=HMACV1&urlSignature=E8UZmDdQL4fVrHqJVc2JxCXDaPmqj9C%2FOSuEjKdxuCo%3D

**Comment by nikhilbadyal** [comment]
These one are expired. Do a fresh run.

**Comment by TeaqariaWTF** [comment]
https://gofile.io/d/R17mVI



https://pipelines.actions.githubusercontent.com/serviceHosts/b94639b4-a22f-4ea1-86cc-459fe813b946/_apis/pipelines/1/runs/37/signedlogcontent/2?urlExpires=2022-12-22T04%3A36%3A51.7439422Z&urlSigningMethod=HMACV1&urlSignature=ZfUpp7sd6bARz3bCkZPwUONP7YI2%2BemjhGHPE7y72lQ%3D

**Comment by TeaqariaWTF** [comment]
did it happen this time

@nikhilbadyal

**Comment by TeaqariaWTF** [comment]
Did you find the source of the problem?

@nikhilbadyal

**Comment by nikhilbadyal** [comment]
Update your fork and Try again.

**Comment by TeaqariaWTF** [comment]
I already did this still not working
@nikhilbadyal

**Comment by nikhilbadyal** [comment]
I checked your action and it actually failed. Weird thing is it failed to download patches/integration from Revanced Repo without even throwing any kind of error. 
Sad part is I'm unable to reproduce this anywhere. So, I'm not sure how what should I try to fix. Also no one else if facing the issue. 
Try reforking the project and see if it works.

**Comment by TeaqariaWTF** [comment]
After deleting the fork and reinstalling it, it started working. One last question, can we change the package name for YouTube?
@ni

**Comment by nikhilbadyal** [comment]
Yes, in the option.toml define. A property named as `YouTube_PackageName`

**Comment by TeaqariaWTF** [comment]
is it this way

![Screenshot_20221225-025521](https://user-images.githubusercontent.com/90970076/209453537-30c3e879-7b59-4d91-a082-bb83a420e58a.png)
@nikhilbadyal

**Comment by nikhilbadyal** [comment]
This is not a package name. Package names are like ~~com.google.android.youtube~~.

**Comment by TeaqariaWTF** [comment]
> 

I don't know exactly where to install them.

**Comment by TeaqariaWTF** [comment]
can you create a sample config

**Comment by nikhilbadyal** [comment]
> > 
> 
> I don't know exactly where to install them.

In option.toml file.

**Comment by TeaqariaWTF** [comment]
can you share the sample config with me

@nikhilbadyal

**Comment by nikhilbadyal** [comment]
Try this if using `Revanced Extended`

```
['patch-options']
'YouTube_AppName' = "ReVanced Extended"

```

or this is using simple `Revanced`

```
['custom-branding']
appName = "YouTube ReVanced"
```

in `option.toml` file

**Comment by TeaqariaWTF** [comment]
i want to change this

![Screenshot_20221225-133630_1](https://user-images.githubusercontent.com/90970076/209464704-bad3d54c-a69b-439f-b5c0-f6360cc582ce.png)

**Comment by nikhilbadyal** [comment]
Updated the comment above. 

If it work, that will be great. If not please, ask in revanced forum. This is a builder repo. Not a revanced support. This Issue has already gone too long. Please be understanding. If everyone keep on querying about revanced here. It'll be hard for me to maintain it anymore.
