### ISSUE TITLE
Infinite loading 

### ISSUE THREAD

**Issue by Andys280** [nikhilbadyal/docker-py-revanced#117]
When i try to watch a video on yt revanced video îs loading Forever . I need to close that video and reopen it . Sometimes works at second oppening, sometimes don t . 
I tried all revanced versions . I ve updated microg . Running on android 12
![Screenshot_20230110-230516793](https://user-images.githubusercontent.com/122404904/211662350-3279591c-2fc8-4478-a907-21398d9b9eaf.jpg)

**Comment by nikhilbadyal** [comment]
Please read [this](https://github.com/nikhilbadyal/docker-py-revanced/blob/main/README.md#L7).


Also try turning off return dislike. Might fix this.
