### ISSUE TITLE
Build action keeps building the same apk 

### ISSUE THREAD

**Issue by imGok** [nikhilbadyal/docker-py-revanced#12]
Hello, youtube_version is latest but it only builds the 17-32-39 version (this version starts to crash this morning for me).

How can I build the last version of yt revanced pls ?

**Comment by imGok** [comment]
Had the last version after reforking and putting no env

**Comment by nikhilbadyal** [comment]
Yes, You dont need to do anything if you want the latest recommended version. All the other options exist if you're going to cook something.
