### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#123]
Add a feature to schedule the building so that it builds and pushes build automatically at a specific time or a specific date.

**Comment by nikhilbadyal** [comment]
Sorry, but there is a reason why revanced team doesn't provides apks directly. For same reason it's hard for me to support automated builds.
But You are very much welcomed to fork the repo and add such support to your fork.

**Comment by ramanveerji** [comment]
> Thats a nice addition to have. 
> Sorry, but I'm afraid to say, there is a reason why revanced team doesn't provides apks directly. For same reason it's hard for me to support automated builds.
> 
> But You are very much welcomed to fork the repo and add such support to your fork.

Actually I want to know how can I add it in my fork?

**Comment by nikhilbadyal** [comment]
@ramanveerji That totally depends on the person who wants to implement it. 

How - 
You need to save the state of earlier run like the version of the last patch. Then every some interval you can compare the current and last version and run if the current  version> last version.
To save the state you can create a new branch where history is stored.

Where - 
1. If you are good with bash scripting you can do all of this in `build-apk.yml` file which can be found in `.github/workflow` folder.
2. If you are more okay with python. You can write the logic in the main file found in source code.

Tip - 
Search for revanced-magisk-module by jhc to see how 1st approach works.

**Comment by ramanveerji** [comment]
Ok will try out
