### ISSUE TITLE
Important info missing from docs

### ISSUE THREAD

**Issue by CattopyTheWeb** [nikhilbadyal/docker-py-revanced#127]
When I followed the docs I got an error `remote: Permission to CattopyTheWeb/docker-py-revanced.git denied to github-actions[bot].` so I went searching for a solution. 
How I fixed it - Settings >> Actions >> Workflow permissions >> Select - Read and write permission's 
I recommend you to add this in the docs to prevent further confusion.

**Comment by CattopyTheWeb** [comment]
please check this out

**Comment by nikhilbadyal** [comment]
Sorry for the wait. Was busy with some other stuff. 
Thanks for such a nice addition. It skipped my mind, those who use actions for first time will have to allow access with this setting. 

I'll update the docs accordingly.

**Comment by CattopyTheWeb** [comment]
Thanks

**Comment by CattopyTheWeb** [comment]
As I myself encountered that error and wasn't sure what to do
