### ISSUE TITLE
Handle API rate limit error

### ISSUE THREAD

**Issue by Fred-Vatin** [nikhilbadyal/docker-py-revanced#131]
When this happens
![image](https://user-images.githubusercontent.com/22337329/219961921-9e535de2-362b-4520-87fa-bcca666c909e.png)
Script should stop with an error

**Comment by nikhilbadyal** [comment]
API limit is already handled and explained [here.](https://github.com/nikhilbadyal/docker-py-revanced/blob/484078efd9a282e19994402f730f0c936d24d661/README.md?plain=1#L266). 
Still I guess it nice to exit instead of going ahead.
