### ISSUE TITLE
revanced spotify ?

### ISSUE THREAD

**Issue by AkumaX1** [nikhilbadyal/docker-py-revanced#16]
now that some patches are out , why not add it ?

**Comment by nikhilbadyal** [comment]
I would love to add Spotify. I even made changes for that. But then I found there is no source to get a clean Spotify APK. Spotify is not on APKMirror or APKPure. So, there is not APK for the patch in the first place.

**Comment by AkumaX1** [comment]
> I would love to add Spotify. I even made changes for that. But then I found there is no source to get a clean Spotify APK. Spotify is not on APKMirror or APKPure. So, there is not APK for the patch in the first place.

uptodown? https://spotify.en.uptodown.com/android

**Comment by nikhilbadyal** [comment]
I'm not sure how safe this is. I dont trust anything other than APKMIRRROR. Is this safe?

**Comment by AkumaX1** [comment]
> I'm not sure how safe this is. I dont trust anything other than APKMIRRROR. Is this safe?

yup its safe , there was one more script that use uptodown . just to be sure do a md5 check .

**Comment by AkumaX1** [comment]
> I'm not sure how safe this is. I dont trust anything other than APKMIRRROR. Is this safe?

here is a section for untouched apks : https://old.reddit.com/r/FREEMEDIAHECKYEAH/wiki/android , just scroll down a bit.

**Comment by nikhilbadyal** [comment]
Great. I'll look into this.

**Comment by nikhilbadyal** [comment]
I have Spotify support. Also check [this](https://github.com/revanced/revanced-patches/issues/621) for updates.
