### ISSUE TITLE
Not building YouTube

### ISSUE THREAD

**Issue by a-dn4n** [nikhilbadyal/docker-py-revanced#164]
Builder fails to produce youtube.apk
Screenshot shows the error I'm getting.
https://ibb.co/3phKQRj

**Comment by IMXEren** [comment]
Same here, forked the repo from scratch & still facing errors.

**Comment by nikhilbadyal** [comment]
Fixed check now.

**Comment by IMXEren** [comment]
Thanks, btw as of inotia00/revanced-patches [V2.173.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.2), MicroG patch has been introduced. Mind taking a look at that?

**Comment by nikhilbadyal** [comment]
Yes, That's what we download and release [now](https://github.com/nikhilbadyal/docker-py-revanced/blob/ddac9dc08fe0f2390b3c6769b58cef589487fca5/src/downloader.py#L246).

**Comment by nikhilbadyal** [comment]
Oh you want to customize mmicrog builds ? If yes, Is there reason for that. Microg is just for login purpose, It's not we interact with that daily.

**Comment by IMXEren** [comment]
Oh, sorry to mention I was talking about the [patches](https://i.imgur.com/Ze6EgOs.png). Can't tell if it works for VancedMicroG but mMicroG works.

**Comment by IMXEren** [comment]
You're correct but I'd like to address the addition of a patch to you. I think the resources you provide with the repo are already enough.

**Comment by Spacellary** [comment]
Customizing the Released mMicroG would be cool 😁
