### ISSUE TITLE
"Invalid app requested to build youtube_music" when enabling Revanced Extended

### ISSUE THREAD

**Issue by tenyuhuang** [nikhilbadyal/docker-py-revanced#198]
Specifying `PATCH_APPS=youtube-music` will throw this exception instead:

```
revanced-builder | 2023-07-04 10:13:17.117 | DEBUG    | src.downloader:apkmirror_latest_version:206 - Trying to download youtube-music's latest version from apkmirror
revanced-builder | 2023-07-04 10:13:17.118 | DEBUG    | src.downloader:apkmirror_latest_version:209 - Invalid app
```

This particular line of code seems to be the issue:

https://github.com/nikhilbadyal/docker-py-revanced/blob/c43bfd4315c0381dcde4074ed9f26c4a623de567/src/patches.py#L49-L52

After changing `youtube-music` to `youtube_music`, it will build without issues.

**Comment by nikhilbadyal** [comment]
Hey @tenyuhuang  thanks for your contribution. 
That's the correct observation. It should be **youtube_music**.
