### ISSUE TITLE
[BUG] Excluded patches are applied to all patched apps

### ISSUE THREAD

**Issue by IMXEren** [nikhilbadyal/docker-py-revanced#200]
The patcher should patch apps with mentioned excluded patches only for the apps stated (`EXCLUDE_PATCH_APP`). But it enforces to patch all other apps with an app excluded patches.

Let me help you understand this with an example and take this `.env` :

```env
KEYSTORE_FILE_NAME=revanced.keystore
ARCHS_TO_BUILD=arm64-v8a
PATCH_APPS=youtube,youtube_music,reddit
REDDIT_VERSION=latest
BUILD_EXTENDED=True
# YOUTUBE_VERSION=latest_supported
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-icon-revancify-red,force-premium-heading,materialyou
YOUTUBE_MUSIC_VERSION=latest
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music-mmt,custom-branding-music-name
```

Apparently, what happens is, the patcher patches the first app (`youtube`) with it's stated exclusions (`custom-branding-icon-revancify-red,force-premium-heading,materialyou`). Next, it should patch the second app (`youtube_music`) with it's own stated exclusions but it gets patched with excluded patches (`'custom-branding-icon-revancify-red', 'force-premium-heading', 'materialyou', 'custom-branding-music-name`). The third app (`reddit`) which doesn't have any exclusions, gets patched with `Excluded patches ['custom-branding-icon-revancify-red', 'force-premium-heading', 'materialyou', 'custom-branding-music-name'] for reddit`. 

Although, those patches are irrelevant for `reddit` app but if these patches happen to exist, they'll be excluded for sure. It's explained by how `youtube_music` got patched with excluding `custom-branding-icon-revancify-red` patch along with `custom-branding-music-name`.

#### Reference

I have tested this `3-4` times on newly created branch with your current `main` branch's resources. Here's the [referenced test](https://github.com/IMXEren/rvx-builds/actions/runs/5479179218) and used this `.env` with it.

```env
KEYSTORE_FILE_NAME=revanced.keystore
ARCHS_TO_BUILD=arm64-v8a
PATCH_APPS=youtube,youtube_music,reddit,reddit_sync,trakt
REDDIT_VERSION=latest
TRAKT_VERSION=latest
EXISTING_DOWNLOADED_APKS=reddit_sync
# ALTERNATIVE_YOUTUBE_MUSIC_PATCHES=custom-branding-music-afn-red,custom-branding-music-revancify-blue,custom-branding-music-mmt
# ALTERNATIVE_YOUTUBE_PATCHES=custom-branding-icon-afn-blue,custom-branding-icon-revancify-blue,custom-branding-icon-mmt
BUILD_EXTENDED=True
# YOUTUBE_VERSION=latest_supported
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-icon-revancify-red,custom-branding-name,force-premium-heading,materialyou
YOUTUBE_MUSIC_VERSION=latest
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music-mmt,custom-branding-music-name
EXCLUDE_PATCH_REDDIT=hide-ads
```

Kindly have a look into this. Thanks!

**Comment by IMXEren** [comment]
Hey @Spacellary, going through your latest Build action, it produces the [same](https://github.com/Spacellary/ReVanced-Extended-Automated-Builds/actions/runs/5473439681/jobs/9966910716#step:5:385) for your `.env`:

```env
# YOUTUBE_VERSION=18.16.39
YOUTUBE_MUSIC_VERSION=latest
KEYSTORE_FILE_NAME=revanced.keystore
BUILD_EXTENDED=True
EXCLUDE_PATCH_YOUTUBE_EXTENDED=materialyou,force-premium-heading,custom-branding-icon-afn-blue,custom-branding-icon-afn-red,custom-branding-icon-revancify-red,custom-branding-icon-revancify-blue # custom-branding-icon-mmt
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music-afn-blue,custom-branding-music-afn-red,custom-branding-music-revancify-red,custom-branding-music-revancify-blue # custom-branding-music-mmt
# ALTERNATIVE_YOUTUBE_PATCHES=custom-branding-icon-afn-blue,custom-branding-icon-revancify,custom-branding-icon-mmt
# ALTERNATIVE_YOUTUBE_MUSIC_PATCHES=custom-branding-music-afn-red,custom-branding-music-revancify,custom-branding-music-mmt
PATCH_APPS=youtube,youtube_music
# ARCHS_TO_BUILD=arm64-v8a,armeabi-v7a
```

**Comment by nikhilbadyal** [comment]
Hey @IMXEren . Fixed by [this](https://github.com/nikhilbadyal/docker-py-revanced/pull/201/commits/4f6fabbd8b8e07542ed1c9ed9d9a154331dac274) .Can you re-run CI-CD using **exclusive-patches** branch and see if fixed.

You can do so by Changing the branch name in 

**Use Workflow from**

<img width="394" alt="image" src="https://github.com/nikhilbadyal/docker-py-revanced/assets/59223300/6afee41f-c8ae-44d1-86ed-1972a8d07b43">

**Comment by IMXEren** [comment]
Working!!
