### ISSUE TITLE
(New Patches Naming Convention Changes) EXCLUDE_PATCH list not applied during patching.

### ISSUE THREAD

**Issue by Spacellary** [nikhilbadyal/docker-py-revanced#203]
Patches from the EXCLUDE_PATCH list in .env aren't actually being excluded, instead the **default** selection of patches is applied.

This seems to be due to the extensive naming and changes to the latest patches, both Official and Extended.

Patches.json changes:
https://github.com/inotia00/revanced-patches/commit/dd3bf00379e214492614b5fc626cdf9524a3d8d4#diff-fa73aa2aea0f1b6bf027000008e8557578170aaa44b32cf7115d57094ccd358a

Fork matching upstream now.

Happens with both YT and YTM.

Run:

YouTube: (L: 146)
https://github.com/Spacellary/ReVanced-Extended-Automated-Builds/actions/runs/5529279990/jobs/10087125076#step:5:146
```
revanced-builder | 2023-07-12 08:23:13.226 | DEBUG    | src.patches:get:164 - Recommended Version for patching youtube is 18.25.40
revanced-builder | 2023-07-12 08:23:13.226 | DEBUG    | src.patches:include_exclude_patch:179 - Excluding patches for app youtube
revanced-builder | 2023-07-12 08:23:13.227 | DEBUG    | src.patches:include_exclude_patch:194 - No excluded patches for youtube
```

YT-Music: (L: 405)
https://github.com/Spacellary/ReVanced-Extended-Automated-Builds/actions/runs/5529279990/jobs/10087125076#step:5:405
```
revanced-builder | 2023-07-12 08:24:34.411 | DEBUG    | src.patches:get_app_configs:207 - Picked youtube_music version latest from env.
revanced-builder | 2023-07-12 08:24:34.411 | DEBUG    | src.patches:include_exclude_patch:179 - Excluding patches for app youtube_music
revanced-builder | 2023-07-12 08:24:34.411 | DEBUG    | src.patches:include_exclude_patch:194 - No excluded patches for youtube_music
```

My .env:

```
# YOUTUBE_VERSION=18.16.39
YOUTUBE_MUSIC_VERSION=latest
KEYSTORE_FILE_NAME=revanced.keystore
BUILD_EXTENDED=True
EXCLUDE_PATCH_YOUTUBE_EXTENDED=materialyou,force-premium-heading,custom-branding-icon-afn-blue,custom-branding-icon-afn-red,custom-branding-icon-revancify-red,custom-branding-icon-revancify-blue # custom-branding-icon-mmt
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music-afn-blue,custom-branding-music-afn-red,custom-branding-music-revancify-red,custom-branding-music-revancify-blue # custom-branding-music-mmt
# ALTERNATIVE_YOUTUBE_PATCHES=custom-branding-icon-afn-blue,custom-branding-icon-revancify,custom-branding-icon-mmt
# ALTERNATIVE_YOUTUBE_MUSIC_PATCHES=custom-branding-music-afn-red,custom-branding-music-revancify,custom-branding-music-mmt
PATCH_APPS=youtube,youtube_music # reddit
# ARCHS_TO_BUILD=arm64-v8a,armeabi-v7a
```

**Comment by Spacellary** [comment]
@IMXEren Can can you confirm this issue with the latest changes?

**Comment by IMXEren** [comment]
Okay, the patch naming convention is changed. So, it's expected.

Hyphens are removed and many more.

**Comment by Spacellary** [comment]
@IMXEren Oh, didn't realize it was to this extent. Thanks for confirming then.

I guess this is it then: https://github.com/inotia00/revanced-patches/commit/dd3bf00379e214492614b5fc626cdf9524a3d8d4#diff-fa73aa2aea0f1b6bf027000008e8557578170aaa44b32cf7115d57094ccd358a

**Comment by nikhilbadyal** [comment]
Fixed by [this](https://github.com/nikhilbadyal/docker-py-revanced/commit/eec2f61469e4ec5450bd4a7eac55f0b2455aecbf). Check if working fine @Spacellary  @IMXEren

**Comment by Spacellary** [comment]
Verified working ✅

Thanks for quick commits! 👍🏻
