### ISSUE TITLE
[Request] Add INCLUDE_PATCH to .env or ENVS

### ISSUE THREAD

**Issue by IMXEren** [nikhilbadyal/docker-py-revanced#206]
Some patches are excluded by default which cause certain patches to be not included while patching. `EXCLUDE_PATCH` works well in case of excluding which is supposed to but can't help with including.

This is a sample `patches.json`. Excluded by default are those patches whose key-value pairs are `"excluded": true`.

**Note: I do not know how the build code executes so no idea if it's already implemented but not the part to *exclusively (force)* include patches except `EXCLUDE_PATCH`(-ES).**
```json
[
  {
    "name": "default-video-quality",
    "description": "Adds ability to set default video quality settings.",
    "version": "0.0.1",
    "excluded": false,
    "options": [],
    "dependencies": [
      "settings"
    ],
    "compatiblePackages": [
      {
        "name": "com.google.android.youtube",
        "versions": [
          "18.20.39",
          "18.21.35",
          "18.22.37",
          "18.23.36",
          "18.24.37",
          "18.25.40"
        ]
      }
    ]
  }
]
```

What do you think??

Thanks

**Comment by IMXEren** [comment]
Kindly don't close this issue. Give me a day to sync the repo and do some tests.

**Comment by nikhilbadyal** [comment]
Sure will keep it open. 

I would also like to improve one thing. Even though all the patches are included by default for particular app. There are some patches which are universal. There is no way to specify those. 
This is how they look like in patches.json

```
{
    "name": "Remove screenshot restriction",
    "description": "Removes the restriction of taking screenshots in apps that normally wouldn't allow it.",
    "version": "0.0.1",
    "excluded": true,
    "options": [],
    "dependencies": [],
    "compatiblePackages": []
  },
```
Here **compatiblePackages** is empty which as it's a universal patch.

I'm thinking to provide to support one more value in **.env** like this.

`INCLUDE_PATCH_<appname>=a,b,c`

Anything you want to suggest on this ?

**Comment by IMXEren** [comment]
Oh, this was it. Yes, it'll be good to have something like this. I'd also like to add that it only `revanced_patches` support this and none of these can be found in `revanced-extended_patches`.

**Comment by IMXEren** [comment]
Thanks for the hard work.
