### ISSUE TITLE
Wrong `facebook` app?

### ISSUE THREAD

**Issue by hlqviet** [nikhilbadyal/docker-py-revanced#231]
The correct one which has patches should be `/apk/facebook-2/messenger` for apkmirror config if I'm not mistaken.

I think it should also be named `messenger` to avoid confusion.

**Comment by IMXEren** [comment]
> The correct one which has patches should be /apk/facebook-2/messenger for apkmirror config if I'm not mistaken.

Thanks for letting us know. You're correct. The older link redirected to Messenger until now.

> I think it should also be named messenger to avoid confusion.

Yes
