### ISSUE TITLE
Sync for Reddit OAuth "ID Not Found"

### ISSUE THREAD

**Issue by Spacellary** [nikhilbadyal/docker-py-revanced#234]
After the latest revanced-patches release the OAuth ID spoofing patch is failing as the Patch name changed and so the value injected from Secrets doesn't match the expected.

Failing at line: [188](https://github.com/Spacellary/ReVanced-Extended-Automated-Builds/actions/runs/5757876862/job/15609570366#step:6:188)

**Reason**: Patch was renamed from "Change OAuth client id" to "Spoof client".

Addressed in https://github.com/nikhilbadyal/docker-py-revanced/pull/235

**Comment by nikhilbadyal** [comment]
Can you check with 2`34-sync-for-reddit-oauth-id-not-found` if this fixes the issues.

**Comment by Spacellary** [comment]
I did check already before and it was a success. 👍
