### ISSUE TITLE
getting error while building some apps

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#257]
I am using original revanced envs
- compilation error is there in youtube music (i am using version=latest and arch arm64)
https://pastecode.io/s/yc53570i

- google recorder is not getting downloaded (i am using version=latest and arch arm64)
https://pastecode.io/s/9fd5vcb9
- inshorts also unable to patch

**Comment by nikhilbadyal** [comment]
1. Issue in Revanced not with the builder. 
2. There is no apk available on [APKMirror](https://www.apkmirror.com/apk/google-inc/google-recorder/google-recorder-4-2-20230608-540477087-release/)
3. Please show error.

**Comment by ramanveerji** [comment]
> 1. Issue in Revanced not with the builder. 
> 2. There is no apk available on [APKMirror](https://www.apkmirror.com/apk/google-inc/google-recorder/google-recorder-4-2-20230608-540477087-release/)
> 3. Please show error. 

1. Ok, thanks for confirming that. 
2. Bundle apks aren't supported? Can make that support in such a way that it can extract arm64 from bundle apks, this will not lead to failure in finding apk.
3. Inshorts was fixed. Maybe i did some mistake. Sorry for that.

**Comment by ramanveerji** [comment]
1 more thing, when we build using Revanced Patches, there is no microg file in assets. It should also be there. Please look into it also.

**Comment by nikhilbadyal** [comment]
> 2\. Bundle apks aren't supported? Can make that support in such a way that it can extract arm64 from bundle apks, this will not lead to failure in finding apk. I have one apk of google recorder but how to patch it. [APKMirror](https://www.apkmirror.com/apk/google-inc/google-recorder/google-recorder-4-2-20230504-529611040-release/#downloads)
They are not just plain zip file with 1 file in it. Inside it there are split apks.

**Comment by nikhilbadyal** [comment]
> 1 more thing, when we build using Revanced Patches, vanced microg is not getting built. It should also be there. Please look into it also.

Revanced doesn't support microg patching.

**Comment by ramanveerji** [comment]
> > 1 more thing, when we build using Revanced Patches, vanced microg is not getting built. It should also be there. Please look into it also.
> 
> Revanced doesn't support microg patching.

Ok is there any way that the vanced microg gets imported from their repo and shows itself in output? Like it gets apk from their own repo and it gets copies in the output.

**Comment by ramanveerji** [comment]
> > 2\. Bundle apks aren't supported? Can make that support in such a way that it can extract arm64 from bundle apks, this will not lead to failure in finding apk. I have one apk of google recorder but how to patch it. [APKMirror](https://www.apkmirror.com/apk/google-inc/google-recorder/google-recorder-4-2-20230504-529611040-release/#downloads)
> 
> 
> They are not just plain zip file with 1 file in it. Inside it there are split apks.

Ok. I thought there would be some way by which those apks gets converted to apk and then gets patched.

**Comment by nikhilbadyal** [comment]
> Ok is there any way that the vanced microg gets imported from their repo and shows itself in output? Like it gets apk from their own repo and it gets copies in the output.

Will add a feature which adds microg to output.

**Comment by nikhilbadyal** [comment]
Check [this](https://github.com/nikhilbadyal/docker-py-revanced#extra-files).

**Comment by ramanveerji** [comment]
> Check [this](https://github.com/nikhilbadyal/docker-py-revanced#extra-files).

So as per the example, it will upload microg.apk and integrations.apk. Correct?

**Comment by nikhilbadyal** [comment]
I have added support to download bundle from APKM and convert it to apk then patch the apk.

**Comment by ramanveerji** [comment]
> I have added support to download bundle from APKM and convert it to apk then patch the apk.

Thanks a lot, now it will help to patch google recorder also.

**Comment by nikhilbadyal** [comment]
Google Recorder is already supported. We use uptodown instead of apkmirror.

**Comment by nikhilbadyal** [comment]
> it is not building google recorder

Sadly, Uptodown itself is [down](https://twitter.com/Uptodown/status/1691773500111921627).

Any we have [switched back to APKMirror](https://github.com/nikhilbadyal/docker-py-revanced/commit/a92de3e6dadc1416dd9f1a60c9be4c38cba12d12) now. We convert bundle to apk and then patch.

Run your workflow again.

**Comment by ramanveerji** [comment]
Now it is working perfectly fine. Finally I can use google recorder now. Thanks.

**Comment by ramanveerji** [comment]
There seems to be some issue as google recorder is not getting installed even it is signed.

**Comment by nikhilbadyal** [comment]
Patch not working. Raise to the revanced team.

**Comment by ramanveerji** [comment]
> Patch not working. Raise to the revanced team.

Okay 👌
