### ISSUE TITLE
Video stop

### ISSUE THREAD

**Issue by MrConqueror** [nikhilbadyal/docker-py-revanced#259]
![Screenshot_2023-08-08-11-59-00-968_app rvx android youtube](https://github.com/nikhilbadyal/docker-py-revanced/assets/102837820/18ae5156-8d78-430d-bb80-1bfbb2388a2e)

Some music video stop at 1:09

**Comment by nikhilbadyal** [comment]
Not builder issue. Try disabling `Spoof param` and enabling `Spoof player parameter`. (Disable and re-enable) in `Miscellaneous` settings.

**Comment by MrConqueror** [comment]
> Not builder issue. Try disabling `Spoof param` and enabling `Spoof player parameter`. (Disable and re-enable) in `Miscellaneous` settings.

thanks dude it's fine now idk what to do lol, I'm expert at this

**Comment by CattopyTheWeb** [comment]
I'm having the same issue. Tried turning off app spoofing but it keeps turning back on

**Comment by MrConqueror** [comment]
@nikhilbadyal 
![Screenshot_2023-08-31-16-40-46-696_app rvx android youtube](https://github.com/nikhilbadyal/docker-py-revanced/assets/102837820/4fa37ed9-63fa-4f91-aaf6-bd80922004ae)
i have another issue whenever i listen music and put it on autoplay then few songs later the video would stop i don't know why
