### ISSUE TITLE
Extra Downloader Failure

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#263]
I have added that extra files env. 
EXTRA_FILES=https://github.com/TeamVanced/VancedMicroG/releases/latest@VancedMicroG.apk
And now it is not even building. I got the following error.

Creating network "docker-py-revanced_default" with the default driver
Pulling revanced (nikhilbadyal/docker-py-revanced:)...
latest: Pulling from nikhilbadyal/docker-py-revanced
Digest: sha256:a1a841443166ba66f087662fd4b43cdeaed3842359f6b1a0e05182cfaffa3e67
Status: Downloaded newer image for nikhilbadyal/docker-py-revanced:latest
Creating revanced-builder ... 
Creating revanced-builder ... done
Attaching to revanced-builder
revanced-builder | Traceback (most recent call last):
revanced-builder |   File "/app/main.py", line 47, in <module>
revanced-builder |     main()
revanced-builder |   File "/app/main.py", line 20, in main
revanced-builder |     extra_downloads(config)
revanced-builder |   File "/app/src/utils.py", line 118, in extra_downloads
revanced-builder |     APP.download(url, config, assets_filter="", file_name=new_file_name)
revanced-builder |   File "/app/src/app.py", line 67, in download
revanced-builder |     url = Github.patch_resource(url, assets_filter)[0]
revanced-builder | IndexError: list index out of range
revanced-builder exited with code 1

**Comment by Spacellary** [comment]
Failed at [actions/runs/5801501183/job/15725901666#step:6:17](https://github.com/Spacellary/ReVanced-Extended-Automated-Builder/actions/runs/5801501183/job/15725901666#step:6:17

```
...
revanced-builder | Traceback (most recent call last):
revanced-builder |   File "/app/main.py", line 47, in <module>
revanced-builder |     main()
revanced-builder |   File "/app/main.py", line 20, in main
revanced-builder |     extra_downloads(config)
revanced-builder |   File "/app/src/utils.py", line 1[18](https://github.com/Spacellary/ReVanced-Extended-Automated-Builder/actions/runs/5801501183/job/15725901666#step:6:19), in extra_downloads
revanced-builder |     APP.download(url, config, assets_filter="", file_name=new_file_name)
revanced-builder |   File "/app/src/app.py", line 67, in download
revanced-builder |     url = Github.patch_resource(url, assets_filter)[0]
revanced-builder | IndexError: list index out of range
...
```

**Comment by nikhilbadyal** [comment]
The library [we use](https://pypi.org/project/lastversion/) to find latest is little buggy causing the error.
