### ISSUE TITLE
resource not accessible by integrations ERROR

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#266]
Run ncipollo/release-action@main 
23 (https://github.com/ramanveerji/docker-py-revanced/actions/runs/5805827794/job/15737655970#step:5:23) 
23 (https://github.com/ramanveerji/docker-py-revanced/actions/runs/5805827794/job/15737655970#step:5:24)Error: Error 403: Resource not accessible by integration

**Comment by nikhilbadyal** [comment]
Not an issue with Builder. Looks like some access issue. 

Have you provided GitHub token in the secrets ?

**Comment by ramanveerji** [comment]
> Not an issue with Builder. Looks like some access issue. 
> 
> Have you provided GitHub token in the secrets ?

Yes. I am using it since the beginning.

**Comment by nikhilbadyal** [comment]
Your token probably isn't privileged enough. Can i have the screenshot of access given to the token.

**Comment by ramanveerji** [comment]
> Your token probably isn't privileged enough. Can i have the screenshot of access given to the token.

![Screenshot_2023-08-11-18-12-35-213_com.microsoft.emmx.png](https://github.com/nikhilbadyal/docker-py-revanced/assets/70764724/a25f7c9a-7dec-409c-9822-46edb91d793c)

**Comment by nikhilbadyal** [comment]
Can you give all the permissions to this token and re run the workflow.

**Comment by ramanveerji** [comment]
> Can you give all the permissions to this token and re run the workflow.

Ok will test right now

**Comment by ramanveerji** [comment]
![image](https://github.com/nikhilbadyal/docker-py-revanced/assets/70764724/1d4736a7-4611-4166-b366-9facc79a0ea1)
This is where the error occurs.

**Comment by nikhilbadyal** [comment]
Can you try [this ](https://stackoverflow.com/a/76869762)solution.

**Comment by ramanveerji** [comment]
> Can you try [this ](https://stackoverflow.com/a/76869762)solution.

This thing fixed that. Thanks. It was working without it earlier.

**Comment by nikhilbadyal** [comment]
Strange if it worked.

I suddenly remembered the issue.I also faced it during the initial days of development and it's already documented. See the last point in README.md

**Comment by ramanveerji** [comment]
> Strange if it worked.
> 
> I suddenly remembered the issue.I also faced it during the initial days of development and it's already documented. See the last point in README.md

I reforked the repo maybe that settings got turned off. Anyways thanks for the reply.
