### ISSUE TITLE
Download Assets from Custom Github Tag

### ISSUE THREAD

**Issue by nikhilbadyal** [nikhilbadyal/docker-py-revanced#267]
[Issue](https://github.com/nikhilbadyal/docker-py-revanced/issues/230#issuecomment-1668263347)

**Comment by nikhilbadyal** [comment]
Added now the ability to download from tags. See example config [here](https://github.com/nikhilbadyal/docker-py-revanced/blob/b1af206dadb18e741de2ccd8cfdb91030a8b530f/.env.example#L22).

@Spacellary @IMXEren

**Comment by Spacellary** [comment]
Good stuff!

**Comment by IMXEren** [comment]
Great!!

I'd like to confirm somethings.
1. Can the resources be sourced locally? Any chances of implementation?
2. Any chance of using something similar in near future due to a better ease in generation.
   
```ini
YOUTUBE_CLI_DL=local,example_cli.rar
YOUTUBE_PATCHES_DL=link,https://example.com
YOUTUBE_PATCHES_JSON_DL=github,owner/repo/version #latest or tag name
```

You neither need to specify any ETA nor this is a enhancement request and just related to some personal projects, I was working on.

**Comment by nikhilbadyal** [comment]
> 1. Can the resources be sourced locally?

Not yet


> 1. Any chances of implementation?

Sure

> 2\. Any chance of using something similar in near future due to a better ease in generation.

I'm thinking something like 
```
YOUTUBE_CLI_DL=local://cli.jar
YOUTUBE_PATCHES_DL=local://patches.jar
YOUTUBE_PATCHES_JSON_DL=local://patches.json
```

**Comment by test-imxone** [comment]
> I'm thinking something like
>
> YOUTUBE_CLI_DL=local://cli.jar
YOUTUBE_PATCHES_DL=local://patches.jar
YOUTUBE_PATCHES_JSON_DL=local://patches.

Awesome idea!!

So that does imply that no changes will be made to github sources for the time being.

**Comment by IMXEren** [comment]
> I'm thinking something like
>
> YOUTUBE_CLI_DL=local://cli.jar
YOUTUBE_PATCHES_DL=local://patches.jar
YOUTUBE_PATCHES_JSON_DL=local://patches.

Awesome idea!!

So that does imply that no changes will be made to github sources for the time being.
