### ISSUE TITLE
Revanced Extended gone Advanced

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#276]
https://github.com/j-hc/revanced-magisk-module/issues/295#issue-1847953851

**Comment by nikhilbadyal** [comment]
Couldn't understand. 
What's the motive behind this issue. 
If it's about informing that extended is archived we are aware of [this](https://github.com/nikhilbadyal/docker-py-revanced/discussions/221#discussioncomment-6643711).

**Comment by ramanveerji** [comment]
> Couldn't understand. 
> What's the motive behind this issue. 
> If it's about informing that extended is archived we are aware of [this](https://github.com/nikhilbadyal/docker-py-revanced/discussions/221#discussioncomment-6643711).

Extended is archived is not the motive.
The motive is to add support for YT-ADVANCED. It looks like Revanced extended has been taken by someone by the name YT-ADVANCED and it is under development. YT-ADVANCED has been added in revancify also.

**Comment by nikhilbadyal** [comment]
We now support any source for patches. Whether it's `yt-advanced` or `ABC`. 

Please read the readme/description of the project.
