### ISSUE TITLE
telegram upload is working but its uploading from the main repo not the fork . 

### ISSUE THREAD

**Issue by AkumaX1** [nikhilbadyal/docker-py-revanced#28]
![librewolf_VJGuR8HjhP](https://user-images.githubusercontent.com/93121473/193458390-6db9cc82-6fae-4a57-b4de-83595b43ab00.png)

**Comment by nikhilbadyal** [comment]
😅 My bad. 
Anyways, it should be fixed by [this](https://github.com/nikhilbadyal/ghaction-telegram-uploader/commit/817b3c1deeb7eab9e742cd0373c420b3912ab73e) commit. 
Can you retry?

**Comment by AkumaX1** [comment]
> 😅 My bad. Anyways, it should be fixed by [this](https://github.com/nikhilbadyal/ghaction-telegram-uploader/commit/817b3c1deeb7eab9e742cd0373c420b3912ab73e) commit. Can you retry?

yup working now . 😄
