### ISSUE TITLE
Support for YT-REX

### ISSUE THREAD

**Issue by soymadip** [nikhilbadyal/docker-py-revanced#293]
As inotia00 stopped homis project, another project is continuing his legacy:- [YT-REX](https://github.com/YT-Advanced)

Please add support for this repo instead/alongside of REVANCED_EXTENDED.

**Comment by nikhilbadyal** [comment]
We support any source for patching resources. See [this](https://github.com/nikhilbadyal/docker-py-revanced/issues/276#issuecomment-1675929644)

Click [here](https://github.com/nikhilbadyal/docker-py-revanced/blob/main/.env.example) to see example envs.
