### ISSUE TITLE
small question

### ISSUE THREAD

**Issue by Pratyay360** [nikhilbadyal/docker-py-revanced#30]
hey i have checked your telegram channel given in the readme section and i have noticed that the apks there have different versions and icon than mine. My fork is syncd with yours and i have compiled them recently.

**Comment by nikhilbadyal** [comment]
Can you give some examples ? What do you mean by different icons and specifically which app are you asking about ?

**Comment by Pratyay360** [comment]
ok thanks for answering

**Comment by nikhilbadyal** [comment]
That's something else. I got to know about revanced extended a few days ago and implemented this a [few days](https://github.com/nikhilbadyal/docker-py-revanced/pull/20) ago.

**Comment by nikhilbadyal** [comment]
Yes, they are the same but you don't need these unless you are building with docker.

**Comment by Pratyay360** [comment]
then how to BUILD_EXTENDED or EXCLUDE_PATCH

**Comment by nikhilbadyal** [comment]
I somehow skipped in docs. If you want to skip an revanced extended patch. Do

`EXCLUDE_PATCH_<REVANCED_APP_EXTENDED`

So simply EXTENDED in the end. You can also have my configuration.

Here is what I use.
```
PATCH_APPS=youtube,twitter,reddit
BUILD_EXTENDED=True
EXCLUDE_PATCH_YOUTUBE=custom-branding,enable-debugging
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue,materialyou
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music
```

**Comment by Pratyay360** [comment]
ok thanks :)

**Comment by Pratyay360** [comment]
Hey not working 
![image](https://user-images.githubusercontent.com/61408566/193900714-7f6b8328-6ce6-40e1-a589-8d446a0aa733.png)

```
PATCH_APPS=youtube,twitter,reddit,youtube_music,Spotify
BUILD_EXTENDED=True
EXCLUDE_PATCH_YOUTUBE=custom-branding,enable-debugging
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music 
```
![image](https://user-images.githubusercontent.com/61408566/193901515-96dd32ff-cf67-44e1-bc22-b8084288df6d.png)

**Comment by Pratyay360** [comment]
> Hey not working ![image](https://user-images.githubusercontent.com/61408566/193900714-7f6b8328-6ce6-40e1-a589-8d446a0aa733.png)
> 
> ```
> PATCH_APPS=youtube,twitter,reddit,youtube_music,Spotify
> BUILD_EXTENDED=True
> EXCLUDE_PATCH_YOUTUBE=custom-branding,enable-debugging
> EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue
> EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music 
> ```
> 
> ![image](https://user-images.githubusercontent.com/61408566/193901515-96dd32ff-cf67-44e1-bc22-b8084288df6d.png)

i have prompted to compile youtube, youtube music, spotify, reddit, twitter but it's uploading ```tiktok``` and ```warnwetter```

**Comment by Pratyay360** [comment]
> write **_S_**potify properly. It should be **spotify** (Small S). And share the debug logs.

doing this worked absolutely fine for me thanks once again:)

**Comment by Pratyay360** [comment]
> write **_S_**potify properly. It should be **spotify** (Small S). I updated the README toosweat_smile. And share the debug logs.

btw logs 
[logs_84.zip](https://github.com/nikhilbadyal/docker-py-revanced/files/9721541/logs_84.zip)

**Comment by Pratyay360** [comment]
hey again faced a problem 
![image](https://user-images.githubusercontent.com/61408566/194248374-782cee33-340d-4bba-915a-fa385d875247.png)
only compiling youtube and youtube music while BUILD_EXTENDED=True flag is true i have seen that [revanced extended](https://github.com/inotia00/revanced-patches/tree/revanced-extended) only compiles youtube and youtube music.

**Comment by nikhilbadyal** [comment]
Its a revanced issue. No app is compiling with revanced.

You can check the status [here](https://github.com/revanced/revanced-patches/issues/725)


YouTube and YouTube music is working because it uses revanced extended.

**Comment by Pratyay360** [comment]
yeah i have seen issue created by you

**Comment by nikhilbadyal** [comment]
Fixed now.
