### ISSUE TITLE
not building single arch

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#343]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

twitter, twitch

### Error log or link to the logs if using Github Action

revanced-builder | 2023-08-28 10:31:42.551 | INFO     | __main__:main:35 - app_name: twitter, app_version: latest, experiment: False, cli_dl: https://github.com/revanced/revanced-cli, patches_dl: https://github.com/revanced/revanced-patches, integrations_dl: https://github.com/revanced/revanced-integrations, patches_json_dl: https://github.com/revanced/revanced-patches, exclude_request: ['change-package-name'], include_request: [], resource: {'cli': 'ab4bafcbf975099ef41b1087b45ea28e040de81bd75e7b2937c634be45f18b42.jar', 'integrations': 'ce127b950b7842b5a1fb027eab73f9c0c73bdea55bdfcde938c28fdadc5e59dd.apk', 'patches': '98f874bc9312a252af3cbbc337ba411fda67efba562d3ea50ce8475eabc3a71c.jar', 'patches_json': 'adff79deced5349ccbbf88fbd08b256a41bb6e3a1a407e05e31c524bb34b68d6.json'}, no_of_patches: 3, keystore_name: rs.keystore, archs_to_build: ['arm64-v8a'], download_file_name: twitter.apk, download_dl: https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=5175601&key=1db3e25090e7b08074610dd83159fa95b1fc018f&forcebaseapk=true, download_source: https://www.apkmirror.com/apk/x-corp/twitter/, package_name: com.twitter.android

It is showing arm64 but after patching the apk has arm64, armeabi, arm64 and 1 more lib.

### ENVS

```Dotenv
#Twitch
TWITCH_ARCHS_TO_BUILD=arm64-v8a
#Twitter
TWITTER_ARCHS_TO_BUILD=arm64-v8a
```

### Additional info

It is showing arm64 but after patching the apk has arm64, armeabi, arm64 and 1 more lib. This is happening both for twitter and twitch.

**Comment by ramanveerji** [comment]
full logs [here ](https://pipelines.actions.githubusercontent.com/serviceHosts/105ec774-245a-4e31-94a8-a7f5af8a27c8/_apis/pipelines/1/runs/45/signedlogcontent/2?urlExpires=2023-08-28T10%3A53%3A16.8082265Z&urlSigningMethod=HMACV1&urlSignature=FmBEV%2BsnZVcaMTMUNmfhU8nZ6kK7dkxtSwrz6gJUpc8%3D)

**Comment by nikhilbadyal** [comment]
Read 2nd point in Note [here](https://github.com/nikhilbadyal/docker-py-revanced#global-archs-to-build).

**Comment by ramanveerji** [comment]
> 

How to know if it is supported?

**Comment by nikhilbadyal** [comment]
See cli docs or ask in issues for the all the cli you know. Revanced official doesn't support that i know. [This](https://github.com/j-hc/revanced-cli) one supports.

**Comment by ramanveerji** [comment]
> See cli docs or ask in issues for the all the cli you know. Revanced official doesn't support that i know. [This](https://github.com/j-hc/revanced-cli) one supports.

So, I can use this cli as env of twitter to get only 1 lib. Correct?

**Comment by nikhilbadyal** [comment]
Old cli. Last updated on 11July. I would suggest not using this option at all or maybe i'm thinking to remove or hide this option for now.

**Comment by ramanveerji** [comment]
> Old cli. Last updated on 11July. I would suggest not using this option at all or maybe i'm thinking to remove or hide this option for now.

Maybe it gets updated after some time, I will wait. If it gets updated then I will try out.
