### ISSUE TITLE
Photomath building error

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#344]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

photomath

### Error log or link to the logs if using Github Action

https://pipelines.actions.githubusercontent.com/serviceHosts/105ec774-245a-4e31-94a8-a7f5af8a27c8/_apis/pipelines/1/runs/45/signedlogcontent/2?urlExpires=2023-08-28T10%3A53%3A16.8082265Z&urlSigningMethod=HMACV1&urlSignature=FmBEV%2BsnZVcaMTMUNmfhU8nZ6kK7dkxtSwrz6gJUpc8%3D

### ENVS

```Dotenv
#Photomath
PHOTOMATH_EXCLUDE_PATCH=change-package-name
PHOTOMATH_ARCHS_TO_BUILD=arm64-v8a
```

**Comment by ramanveerji** [comment]
logs are here
https://pastecode.io/s/o43opzqz

**Comment by nikhilbadyal** [comment]
Can you paste `.env `completely ? Also try updating your fork running again. It works for me.

**Comment by ramanveerji** [comment]
> Can you paste `.env `completely ? Also try updating your fork running the builder again. It works for me.

I didn't add any thing extra than the archs to build and exclude patch. I am using global cli, integration and patches from revanced original only.
Anyways, I have updated the fork, let me try building again.

**Comment by ramanveerji** [comment]
#Global ENVS
PATCH_APPS=youtube,youtube_music,inshorts,twitter,lightroom,duolingo,twitch,photomath
GLOBAL_KEYSTORE_FILE_NAME=rs.keystore
GLOBAL_CLI_DL=https://github.com/revanced/revanced-cli
GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches
GLOBAL_PATCHES_JSON_DL=https://github.com/revanced/revanced-patches
GLOBAL_INTEGRATIONS_DL=https://github.com/revanced/revanced-integrations
PERSONAL_ACCESS_TOKEN=******
GLOBAL_ARCHS_TO_BUILD=arm64-v8a

#Youtube
YOUTUBE_EXCLUDE_PATCH=custom-branding
YOUTUBE_ARCHS_TO_BUILD=arm64-v8a,armeabi-v7a

#Youtube Music
YOUTUBE_MUSIC_EXCLUDE_PATCH=custom-branding

#Photomath

#Lightroom

#Inshorts

#Twitter
TWITTER_ARCHS_TO_BUILD=arm64-v8a

#Duolingo
DUOLINGO_ARCHS_TO_BUILD=arm64-v8a

#Twitch
TWITCH_ARCHS_TO_BUILD=arm64-v8a

#Extra Files
EXTRA_FILES=https://github.com/TeamVanced/VancedMicroG/releases/latest@VancedMicroG.apk




going to try with this now

**Comment by ramanveerji** [comment]
again got this error

[patches/releases/download/v2.189.0/patches.json.](https://github.com/ReVanced/revanced-patches/releases/download/v2.189.0/patches.json.) File already exists or dry running.
revanced-builder | 2023-08-28 14:02:18.593 | INFO     | src.app:download_apk_for_patching:59 - Downloading apk to be patched by scrapping
revanced-builder | 2023-08-28 14:02:18.649 | ERROR    | __main__:main:44 - Failed to build photomath because of Message - Default Error message. Url - https://www.apkmonk.com/app/com.microblink.photomath/
revanced-builder | Traceback (most recent call last):
revanced-builder | 
revanced-builder |   File "/app/main.py", line 49, in <module>
revanced-builder |     main()
revanced-builder |     └ <function main at 0x7f01bcf6c4a0>
revanced-builder | 
revanced-builder | > File "/app/main.py", line 33, in main
revanced-builder |     app.download_apk_for_patching(config)
revanced-builder |     │   │                         └ <src.config.RevancedConfig object at 0x7f01bcdbd710>
revanced-builder |     │   └ <function APP.download_apk_for_patching at 0x7f01bbd0f1a0>
revanced-builder |     └ <src.app.APP object at 0x7f01bbc0c050>
revanced-builder | 
revanced-builder |   File "/app/src/app.py", line 69, in download_apk_for_patching
revanced-builder |     self.download_file_name, self.download_dl = downloader.download(self.app_version, self)
revanced-builder |     │    │                   │    │             │          │        │    │            └ <src.app.APP object at 0x7f01bbc0c050>
revanced-builder |     │    │                   │    │             │          │        │    └ '8.20.0'
revanced-builder |     │    │                   │    │             │          │        └ <src.app.APP object at 0x7f01bbc0c050>
revanced-builder |     │    │                   │    │             │          └ <function Downloader.download at 0x7f01bbd85760>
revanced-builder |     │    │                   │    │             └ <src.downloader.apkmonk.ApkMonk object at 0x7f01bab17490>
revanced-builder |     │    │                   │    └ ''
revanced-builder |     │    │                   └ <src.app.APP object at 0x7f01bbc0c050>
revanced-builder |     │    └ ''
revanced-builder |     └ <src.app.APP object at 0x7f01bbc0c050>
revanced-builder | 
revanced-builder |   File "/app/src/downloader/download.py", line 127, in download
revanced-builder |     file_name, app_dl = self.specific_version(app, version)
revanced-builder |                         │    │                │    └ '8.20.0'
revanced-builder |                         │    │                └ <src.app.APP object at 0x7f01bbc0c050>
revanced-builder |                         │    └ <function ApkMonk.specific_version at 0x7f01baad4f40>
revanced-builder |                         └ <src.downloader.apkmonk.ApkMonk object at 0x7f01bab17490>
revanced-builder | 
revanced-builder |   File "/app/src/downloader/apkmonk.py", line 79, in specific_version
revanced-builder |     raise APKMonkAPKDownloadError(
revanced-builder |           └ <class 'src.exceptions.APKMonkAPKDownloadError'>
revanced-builder | 
revanced-builder | src.exceptions.APKMonkAPKDownloadError: Message - Default Error message. Url -

**Comment by nikhilbadyal** [comment]
I looked into it. Apparently APKMonk is blocking request which comes from GitHub Action.
I have no plans to fix this for now. You can build this locally if you want to patch.

**Comment by nikhilbadyal** [comment]
This can be bypassed with selenium or headless browser. Happy to accept PR if someone want to implement this.

**Comment by ramanveerji** [comment]
> I looked into it. Apparently APKMonk is blocking request which comes from GitHub Action. I have no plans to fix this for now. You can build this locally if you want to patch.

hmm okay

**Comment by ramanveerji** [comment]
> This can be bypassed with selenium or headless browser. Happy to accept PR if someone want to implement this.

I hope someone can look onto this.

**Comment by ramanveerji** [comment]
I think you added something new bro, now the action build and upload is not working.

**Comment by ramanveerji** [comment]
![image](https://github.com/nikhilbadyal/docker-py-revanced/assets/70764724/6a78b823-669b-431a-a25a-6c0987dd1c81)
It is not building revanced apps now

**Comment by ramanveerji** [comment]
> @ramanveerji Fixed.

thanks

**Comment by ramanveerji** [comment]
Brother update the photomath link from apkmonk to apksos

https://apksos.com/download-app/com.microblink.photomath

Photomath is available on apksos, this might fix photomath issue.

**Comment by nikhilbadyal** [comment]
Doesn't even have the version (8.20.0) which revanced support.

**Comment by ramanveerji** [comment]
Revanced now supports latest version of photomath.

**Comment by nikhilbadyal** [comment]
I would like to keep the source same. You however free to do change the sources as per your convenience. Please read the docs. How to configure [any](https://github.com/nikhilbadyal/docker-py-revanced#any-patch-apps) any supported source.

**Comment by nikhilbadyal** [comment]
Example env
```
PHOTOMATH_DL_SOURCE=https://apksos.com/download-app/com.microblink.photomath
PHOTOMATH_PACKAGE_NAME=com.microblink.photomath
```

**Comment by ramanveerji** [comment]
> Example env
> ```
> PHOTOMATH_DL_SOURCE=https://apksos.com/download-app/com.microblink.photomath
> PHOTOMATH_PACKAGE_NAME=com.microblink.photomath
> ```

Thanks for explaining this. I have read the docs but I was having a doubt, now it is cleared. Thanks a lot.
