### ISSUE TITLE
Help regarding scheduling 

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#373]
I have tried to add schedule cron job in workflow but the action always fail during scheduled workflow. Can you help me how to fix it?.

**Comment by nikhilbadyal** [comment]
What's the error you are getting ?

**Comment by nikhilbadyal** [comment]
Duplicate of https://github.com/nikhilbadyal/docker-py-revanced/issues/123#issuecomment-1407660085

**Comment by nikhilbadyal** [comment]
Open a discussion if you want some help with some issue.

**Comment by ramanveerji** [comment]
> What's the error you are getting ?

Can you please check this error once. I just added the schedule cron and didn't touched this code, still getting this.

The template is not valid. .github/workflows/build-apk.yml (Line: 54, Col: 25): Unexpected value '',.github/workflows/build-apk.yml (Line: 55, Col: 22): Unexpected value ''
