### ISSUE TITLE
mini thumbnail 

### ISSUE THREAD

**Issue by MrConqueror** [nikhilbadyal/docker-py-revanced#384]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Description

![Screenshot_2023-09-29-15-09-59-950_app rvx android youtube](https://github.com/nikhilbadyal/docker-py-revanced/assets/102837820/a2aad9e2-65ac-49f8-ad05-872eec0a8ae0)
i seek then there should be mini thumbnail shown like YouTube app

### Motivation

.

### Additional Context

.

**Comment by IMXEren** [comment]
> You are asking something that is out of domain of @nikhilbadyal . It's expected for you to use respective forums for support.

For your question, this is a known issue due to `Spoof player parameters` patch to fix buffering issues. Fortunately, it's fixed in RVX with lower quality and I think the upgrade in quality is in upcoming patch updates.

**Comment by nikhilbadyal** [comment]
Follow issue [guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support).

**Comment by MrConqueror** [comment]
> Follow issue [guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support).

![Screenshot_2023-10-02-12-19-30-960_app rvx android youtube](https://github.com/nikhilbadyal/docker-py-revanced/assets/102837820/62e5412a-215b-4b9f-b31f-18c08885307b) 
I can't just figured why this is always happening, Like i searched a song time of my life and played the playlist then i listened while doing chores but after the song Pricetag it stopped as you can see there's a notification that says "Video paused. Continue Watching?' Why this thing suddenly pop up? i am tired of it, this is always happening, i am tired of getting up to tap Yes, so that the Video play again. is there a setting to resolve this? or this is an app issue?? but i suspect that the cause of this is the notification from TikTok, i guess whenever i get notifications from anything the YouTube Video stop and I don't want it. is there a setting to get rid of this how to resolve this issue?
