### ISSUE TITLE
[Bug/Feature] App patch version not on APKMirror

### ISSUE THREAD

**Issue by IMXEren** [nikhilbadyal/docker-py-revanced#385]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

youtube_music

### Error log or link to the logs if using Github Action

https://github.com/nikhilbadyal/docker-py-revanced/actions/runs/6355836070/job/17264481031#step:6:1098

```
revanced-builder | 2023-09-29 18:53:19.667 | INFO     | src.app:download_apk_for_patching:56 - Downloading apk to be patched by scrapping
revanced-builder | 2023-09-29 18:53:20.242 | ERROR    | __main__:main:51 - Failed to build youtube_music because of Unable to downloaded assets. Reason - <!DOCTYPE html>
revanced-builder | <html lang="en-US" class="auto-theme">
revanced-builder | <head>
revanced-builder | <meta charset="UTF-8">
revanced-builder | <meta name="viewport" content="width=device-width" />
revanced-builder | <meta name="theme-color" content="#FF8B14">
revanced-builder | 
revanced-builder | <script type="text/javascript" async="true">
revanced-builder |             var quantcast_host="apkmirror.com"
```

### ENVS

```Dotenv
### Global:
DRY_RUN=False
GLOBAL_ARCHS_TO_BUILD=arm64-v8a
PATCH_APPS=youtube,youtube_music,reddit,trakt,twitter
EXTRA_FILES=https://github.com/kazimmt/mmicrog/releases/latest@kazimmt_mMicroG.apk

### YouTube Music:
# YOUTUBE_MUSIC_VERSION=latest_supported
# YOUTUBE_MUSIC_KEYSTORE_FILE_NAME=revanced.keystore
YOUTUBE_MUSIC_ARCHS_TO_BUILD=arm64-v8a,armeabi-v7a
YOUTUBE_MUSIC_CLI_DL=https://github.com/inotia00/revanced-cli/releases/latest
YOUTUBE_MUSIC_PATCHES_DL=https://github.com/inotia00/revanced-patches/releases/latest
YOUTUBE_MUSIC_PATCHES_JSON_DL=https://github.com/inotia00/revanced-patches/releases/latest
YOUTUBE_MUSIC_INTEGRATIONS_DL=https://github.com/inotia00/revanced-integrations/releases/latest
YOUTUBE_MUSIC_EXCLUDE_PATCH=custom-branding-icon-mmt,custom-branding-icon-revancify-red,custom-branding-music-name,enable-debug-logging,custom-package-name
```

### Additional info

The latest supported patch version for RVX is `6.21.51` which isn't available in APKM.

I request a feature implementation to fallback to a next supported version, if viable. Due to download error log, I tagged this issue as `[BUG]`.

CC
@Spacellary

**Comment by Spacellary** [comment]
Seems to have sorted itself now that the APK has been uploaded but that'd be a good addition to avoid failed builds/having to rebuild manually.

**Comment by nikhilbadyal** [comment]
I'm don't think builder should try to cover every length and breadth just for some minor edge cases. 

Falling back to 2nd or to 3rd or nth source isn't something I see very useful.

Especially 
1. When we allow specifying custom download url.
2. When most of the sources are updated within few hours.
3. APKMirror is generally the first one to have latest version. If things aren't there probably not going to found anywhere.

And it will just add a maintenance burden.

**Comment by IMXEren** [comment]
I meant going down the supported version of the already using source.

**Comment by nikhilbadyal** [comment]
It's already mentioned in the [README.md](https://github.com/nikhilbadyal/docker-py-revanced/blob/eb9214700898c9aee50ea2e7f83cbddbcdf82cb5/README.md?plain=1#L236) that tool will build latest only. 

I don't see it much useful anyways as it's only matter of time when release is available.

**Comment by nikhilbadyal** [comment]
If you want to contribute PR is appreciated.

**Comment by IMXEren** [comment]
I want to but I'm incapable and especially doesn't want to break the code.

I'll leave the decision to close this issue to you.

**Comment by Spacellary** [comment]
It's one of those things that fix themselves after a short amount of time usually, worst case scenario I guess making a temporary branch to build an specific version if you really need the latest patches isn't that bad, personally I don't feel too strongly about it.

**Comment by IMXEren** [comment]
Yeah, you both are right about it. And again there are other issues that must be looked upon.
