### ISSUE TITLE
[Bug] CLI v4 Support

### ISSUE THREAD

**Issue by IMXEren** [nikhilbadyal/docker-py-revanced#387]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

sync,trakt,twitter

### Error log or link to the logs if using Github Action

https://github.com/IMXEren/rvx-builds/actions/runs/6424702072/job/17445874341#step:6:598
https://github.com/IMXEren/rvx-builds/actions/runs/6424838497/job/17446309277

```
revanced-builder | 2023-10-05 21:53:18.679 | DEBUG    | src.downloader.download:_download:62 - Downloaded sync.apk
revanced-builder | 2023-10-05 21:53:18.680 | INFO     | __main__:main:42 - app_name: sync, app_version: v23.06.30-13:39, experiment: False, cli_dl: https://github.com/revanced/revanced-cli/releases/latest, patches_dl: https://github.com/revanced/revanced-patches/releases/latest, integrations_dl: https://github.com/revanced/revanced-integrations/releases/latest, patches_json_dl: https://github.com/revanced/revanced-patches/releases/latest, exclude_request: [], include_request: [], resource: {'cli': '8afdf1bc1e7c1bdfae44925815e1125b580d3fa29aef1b0ca3ac2bc1ca48040f.jar', 'integrations': '86b0a48fdfac72a209a52f4e7087a5512dd0a200117ac4d7bc5819ea2d2ae166.apk', 'patches': '56d04c6c214c14ac14550289a7f35ccd0724a67b91123dd1134b80b9198db6a8.jar', 'patches_json': 'f0487449d2b7718c87eddeb647e96c21b8d85be26a47d3803795930a238df839.json'}, no_of_patches: 3, keystore_name: revanced.keystore, archs_to_build: ['arm64-v8a'], download_file_name: sync.apk, download_dl: https://www.apkmirror.com/wp-content/themes/APKMirror...
revanced-builder | 2023-10-05 21:53:18.964 | DEBUG    | src.parser:is_new_cli:133 - Old cli
revanced-builder | 2023-10-05 21:53:18.964 | DEBUG    | src.parser:patch_app:1[84](https://github.com/IMXEren/rvx-builds/actions/runs/6424838497/job/17446309277#step:6:84) - Sending request to revanced cli for building with args java ['-jar', PosixPath('apks/8afdf1bc1e7c1bdfae44925815e1125b580d3fa29aef1b0ca3ac2bc1ca48040f.jar'), '-a', PosixPath('apks/sync.apk'), '-b', PosixPath('apks/56d04c6c214c14ac14550289a7f35ccd0724a67b91123dd1134b80b9198db6a8.jar'), '-m', PosixPath('apks/86b0a48fdfac72a209a52f4e7087a5512dd0a200117ac4d7bc5819ea2d2ae166.apk'), '-o', PosixPath('apks/Re-sync-v230630-1339-output.apk'), '--keystore', PosixPath('apks/revanced.keystore'), '--options', PosixPath('apks/options.json'), '-i', 'disable-ads', '-i', 'disable-sync-for-lemmy-bottom-sheet', '-i', 'spoof-client']
revanced-builder | Unknown options: '-a', 'apks/sync.apk', '-b', 'apks/56d04c6c214c14ac14550289a7f35ccd0724a67b91123dd1134b80b9198db6a8.jar', '-m', 'apks/86b0a48fdfac72a209a52f4e7087a5512dd0a200117ac4d7bc5819ea2d2ae166.apk', '-o', 'apks/Re-sync-v230630-1339-output.apk', '--keystore', 'apks/revanced.keystore', '--options', 'apks/options.json', '-i', 'disable-ads', '-i', 'disable-sync-for-lemmy-bottom-sheet', '-i', 'spoof-client'
nced-builder | Usage: revanced-cli [-hV] [COMMAND]
revanced-builder | Command line application to use ReVanced
revanced-builder |   -h, --help      Show this help message and exit.
revanced-builder |   -V, --version   Print version information and exit.
revanced-builder | Commands:
revanced-builder |   list-patches  List patches from supplied patch bundles
revanced-builder |   patch         Patch an APK file
revanced-builder |   options       Generate options file from patches
revanced-builder |   utility       Commands for utility purposes
revanced-builder | 2023-10-05 21:53:19.252 | INFO     | src.parser:patch_app:193 - Patching completed for app app_name: sync, app_version: v23.06.30-13:39, experiment: False, cli_dl: https://github.com/revanced/revanced-cli/releases/latest, patches_dl: https://github.com/revanced/revanced-patches/releases/latest, integrations_dl: https://github.com/revanced/revanced-integrations/releases/latest, patches_json_dl: https://github.com/revanced/revanced-patches/releases/latest, exclude_request: [], include_request: [], resource: {'cli': '8afdf1bc1e7c1bdfae44925815e1125b580d3fa29aef1b0ca3ac2bc1ca48040f.jar', 'integrations': '86b0a48fdfac72a209a52f4e7087a5512dd0a200117ac4d7bc5819ea2d2ae166.apk', 'patches': '56d04c6c214c14ac14550289a7f35ccd0724a67b91123dd1134b80b9198db6a8.jar', 'patches_json': 'f0487449d2b7718c87eddeb647e96c21b8d[85](https://github.com/IMXEren/rvx-builds/actions/runs/6424838497/job/17446309277#step:6:85)be26a47d3803795[93](https://github.com/IMXEren/rvx-builds/actions/runs/6424838497/job/17446309277#step:6:93)0a238df839.json'}, no_of_patches: 3, keystore_name: revanced.keystore, archs_to_build: ['arm64-v8a'], download_file_name: sync.apk, download_dl: https://www.apkmir.../
revanced-builder exited with code 0
```

### ENVS

```Dotenv
### Global:
DRY_RUN=False
GLOBAL_ARCHS_TO_BUILD=arm64-v8a
PATCH_APPS=sync,trakt,twitter
EXTRA_FILES=https://github.com/kazimmt/mmicrog/releases/latest@kazimmt_mMicroG.apk

# Default config for apps
```

### Additional info

This only happens for apps using patch resources of ReVanced, inferred out of 3-5 runs of same `.env`.

Can you also confirm, @Spacellary?

**Comment by nikhilbadyal** [comment]
Somehow the builder is think you are using [old cli](https://github.com/IMXEren/rvx-builds/actions/runs/6424702072/job/17445874341#step:6:600) which has old syntax. Will take look.

**Comment by nikhilbadyal** [comment]
It's because v4 is out now and had a check only for [v3](https://github.com/nikhilbadyal/docker-py-revanced/blob/d3595e0ce8c9583da95ce5b6f72012e7741db485/src/parser.py#L130). I think it's time to remove v2 CLI support.

**Comment by Spacellary** [comment]
Oh.

@IMXEren I only tried with Sync and it worked out tbh, but that was yesterday.

https://github.com/Spacellary/ReVanced-Extended-Automated-Builder/actions/runs/6412517789/job/17409959623#step:6:603

https://github.com/Spacellary/ReVanced-Extended-Automated-Builder/actions/runs/6412517789/job/17409959623#step:6:604

**Comment by Spacellary** [comment]
@nikhilbadyal Possible to keep V2, V3 and V4 supported with additional, more scalable tests?

The fact that your tool is so easy to use just by pointing to the correct resources is such a nice thing, ideally that shouldn't be lost.

"Please support my unsupported use case"

Jk, but well... :')

**Comment by Spacellary** [comment]
@nikhilbadyal 

Worst case scenario maybe automatic detection can only be V3 or higher...

But maybe add a manual .env variable, that if present can override the automatic version check, as in CLI_VERSION=V2, V3, V4, V5

And have the set command line behaviors for each VERSION value applied during patching?

Hmm

**Comment by IMXEren** [comment]
Kinda... although I'd prefer functionality over complexities.

This can be a possible solution while ReVanced CLI is being experimented.

Let's see what dev thinks.

**Comment by nikhilbadyal** [comment]
Every piece of code has some life. I'll try to keep it for now. But someday will remove it when it becomes a burden to maintain. Basically where there is 3rd variant of command options.

They also for some reason decided to make [old keystore unusable](https://github.com/ReVanced/revanced-cli/issues/272) without patch work. Handled that as well.

**Comment by IMXEren** [comment]
Acceptable. Thanks

**Comment by IMXEren** [comment]
@Spacellary , Just to let you know this breaks inotia00/revanced-cli. Would he do something about it?

**Comment by nikhilbadyal** [comment]
I have added a temp patch for [now](https://github.com/nikhilbadyal/docker-py-revanced/pull/390/files#diff-f3801dd467fe03200aeee0231f8d75c571a23d688f3372e6a841565a3c46f69fR176). I hope he handles it. It's a pain to maintain so many things.

**Comment by IMXEren** [comment]
Understandable and that's why I didn't request you directly.

**Comment by nikhilbadyal** [comment]
Looks like they also broke how patch names are expected. Earlier Revanced CLI worked with both format **-** and **space**. Now it [doesn't](https://github.com/ReVanced/revanced-cli/commit/80a8d88406b2b04d13dca4fb0d7d7d62e1910317).

**Comment by IMXEren** [comment]
Damn, I just created another issue for that.

**Comment by Spacellary** [comment]
> Looks like they also broke how patch names are expected. Earlier Revanced CLI worked with both format - and space. Now it doesn't.

More brilliant decisions...

**Comment by nikhilbadyal** [comment]
Fixed in v4 branch. Check if working @Spacellary @IMXEren 

Users now need to specify the type of patches, whether they are space separated or - separated. The default is space separated. 

Inoria00 users need to provide space formatted= False. Check readme to understand requirements.

**Comment by IMXEren** [comment]
I'm currently unavailable to test & report.

**Comment by Spacellary** [comment]
@nikhilbadyal Thanks you so much for the patch! Enjoy your weekend 🥳 

Working here -- [actions/runs/6442014436/job/17492391715](https://github.com/Spacellary/ReVanced-Extended-Automated-Builder/actions/runs/6442014436/job/17492391715) -- patching with both RV and RVX, using per **APP**_SPACE_FORMATTED_PATCHES=False for applications with inotia00 source.

**Comment by Spacellary** [comment]
@nikhilbadyal @IMXEren 

Already been a few hours since latest rvx-patches released, tested and **inotia00** has moved to the CLI-v4, and thus his patches can be referenced without the need for `APP_SPACE_FORMATTED_PATCHES=False` anymore.
___

Using only the `GLOBAL_SPACE_FORMATTED_PATCHES=True` = ✅

@inotia00 👀 🥳

**Comment by Spacellary** [comment]
@nikhilbadyal 

> CLI v4.0.2 I released today referred to this and changed the default keystore alias and password to the old values

Welp.
