### ISSUE TITLE
Excluded patches are still getting included

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#393]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

youtube

### Error log or link to the logs if using Github Action

https://github.com/ramanveerji/docker-py-revanced/actions/runs/6443500388/job/17495517030#step:6:76

### ENVS

```Dotenv
YOUTUBE_EXCLUDE_PATCH=Custom branding
```

**Comment by IMXEren** [comment]
Use `custom-branding`.

Format is still the same that's why `_SPACE_FORMATTED_PATCHES` was added.

**Comment by ramanveerji** [comment]
> Use `custom-branding`.
> 
> Format is still the same that's why `_SPACE_FORMATTED_PATCHES` was added.

Thanks for helping, it is fixed now, I was confused and thought we have to add the space in patch name also.
