### ISSUE TITLE
Extra files are not getting uploaded 

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#407]
I have added vanced apk in extra files but it is not getting uploaded. Please check it.
EXTRA_FILES=https://github.com/TeamVanced/VancedMicroG/releases/latest@VancedMicroG.apk

**Comment by nikhilbadyal** [comment]
Read docs and provide URL properly. See example provided in the docs.

 **EXTRA_FILES=`https://github.com/inotia00/mMicroG/releases/latest@mmicrog.apk`,https://github.com/revanced/revanced-integrations@integrations.apk**

**Comment by ramanveerji** [comment]
> Read docs and provide URL properly. See example provided in the docs.
> 
>  **EXTRA_FILES=`https://github.com/inotia00/mMicroG/releases/latest@mmicrog.apk`,https://github.com/revanced/revanced-integrations@integrations.apk**

That's extended microg, I have added vanced microg. The link is same, earlier it was getting uploaded but now it is not.

**Comment by nikhilbadyal** [comment]
Share complete env then. Make sure to follow the issue template.

**Comment by IMXEren** [comment]
@ramanveerji is right about this.

[Action](https://github.com/IMXEren/rvx-builds/actions/runs/6828083448/job/18571544758) Tested on fresh fork with env:

```env
PATCH_APPS=trakt
EXTRA_FILES=https://github.com/kazimmt/mmicrog/releases/latest@kazimmt_mMicroG.apk
```

[Built Release](https://github.com/IMXEren/rvx-builds/releases/tag/Build-2023.11.10-23.25.33)

**Comment by ramanveerji** [comment]
> Share complete env then. Make sure to follow the issue template.


PATCH_APPS=youtube
GLOBAL_CLI_DL=https://github.com/revanced/revanced-cli
GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches
GLOBAL_PATCHES_JSON_DL=https://github.com/revanced/revanced-patches
GLOBAL_INTEGRATIONS_DL=https://github.com/revanced/revanced-integrations
PERSONAL_ACCESS_TOKEN=************
GLOBAL_ARCHS_TO_BUILD=arm64-v8a
GLOBAL_SPACE_FORMATTED_PATCHES=true

#Youtube
YOUTUBE_EXCLUDE_PATCH=custom-branding
YOUTUBE_ARCHS_TO_BUILD=arm64-v8a,armeabi-v7a

#Extra Files
EXTRA_FILES=https://github.com/TeamVanced/VancedMicroG/releases/latest@VancedMicroG.apk
