### ISSUE TITLE
Add patches changelog

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#413]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Description

When the builder releases a new build, it shows the following in telegram

New release(s) :party
See changelog _here_ (here is a hyperlink to the forked repo)

Is it possible to change the _here_ hyperlink to that of patches changelog that are used while building revanced instead of the forked repo release section?
![Screenshot_2023-11-30-13-32-26-815_org telegram plus](https://github.com/nikhilbadyal/docker-py-revanced/assets/70764724/25c35d09-5fbd-4b06-9a8d-84fa7d7d5a7e)

### Motivation

This will help to know the which revanced version patch has been applied instead of forwarding to the github repo release page

**Comment by nikhilbadyal** [comment]
[Hyper-link in telegram messages](https://t.me/c/1849270826/4219) will point to the release section now (for root message) and release section contains appropriate links to the patch resources.

**Comment by ramanveerji** [comment]
> [Hyper-link in telegram messages](https://t.me/c/1849270826/4219) will point to the release section now (for root message) and release section contains appropriate links to the patch resources.

Can you share screenshot of how it looks? That channel or group must be private. Is it pointing towards the revanced patches release section?

**Comment by nikhilbadyal** [comment]
> That channel or group must be private.

https://t.me/revanced_apkss

Check this.

**Comment by ramanveerji** [comment]
> > That channel or group must be private.
> 
> https://t.me/revanced_apkss
> 
> Check this.

Isn't it possible to just add the desired link on **Here** , like from an env var?

**Comment by IMXEren** [comment]
Hey @ramanveerji , 

I do this using my own _Update Checker files_ and produce release builds with [changelogs](https://github.com/IMXEren/rvx-builds/releases).

You may use or have a look at them. Create or replace your repo files with these:
  - [`.github/workflows/update_v2.yml`](https://pastebin.pl/view/raw/cc2b0d71)
  - [`scripts/check_updates.py`](/scripts/check_updates.py)
  - [`.github/workflows/build-apk.yml`](https://pastebin.pl/view/raw/e9d9a2a8) (Edited `L38, L74, L88`)

For setup, run `update_v2.yml` workflow.

**Comment by ramanveerji** [comment]
> Hey @ramanveerji , 
> 
> I do this using my own _Update Checker files_ and produce release builds with [changelogs](https://github.com/IMXEren/rvx-builds/releases).
> 
> You may use or have a look at them. Create or replace your repo files with these:
>   - [`.github/workflows/update_v2.yml`](https://pastebin.pl/view/raw/cc2b0d71)
>   - [`scripts/check_updates.py`](/scripts/check_updates.py)
>   - [`.github/workflows/build-apk.yml`](https://pastebin.pl/view/raw/e9d9a2a8) (Edited `L38, L74, L88`)
> 
> For setup, run `update_v2.yml` workflow.

Actually, what I want to do is whenever the new build gets pushed, the hyperlink that is set in the word "here" in message "New Release(s)🥳
See Changelog here"
, it should not head over to the releases section of this fork rather it should redirect to the releases section of the patches used. For example if i use original revanced patches, it should be like the following in telegram. 

New Release(s)🥳
See Changelog [here](https://github.com/ReVanced/revanced-patches/releases/)

**Comment by IMXEren** [comment]
That is what I meant by "have a look at them". These scripts read all the patch_dl links pointing to github.com and generate a changelog.md, which is later on produced as the release tag body.

With this changelog.md, you may try to upload this document to your telegram or whatever you desire.

**Comment by nikhilbadyal** [comment]
> env var

That's how it is.  **MESSAGE_ROOT**  and **MESSAGE_NON_ROOT** env [controls](https://github.com/nikhilbadyal/docker-py-revanced/blob/e75e591ba928656adb9b1c1489a84d51a7f38411/.github/workflows/build-apk.yml#L116) what will be sent to the telegram for root & non-root builds respectively.

This variable(secret) expects a text(Markdown supported).


This is how my secrets look like which is use for [my](https://t.me/revanced_apkss) telegram channel.

<img width="1221" alt="Secrets Screenshot" src="https://github.com/nikhilbadyal/docker-py-revanced/assets/59223300/5c0c15f3-fdf7-4a58-a773-702d55a6ed13">


If you want the hyper link to point to the patch resource. You can also add like above. 

Example for non-root builds - 

New Release(s) for Non-Root Users🚀\n\n See Changelog [here](https://github.com/inotia00/revanced-patches/releases/latest) and get the apks  [here](https://github.com/nikhilbadyal/docker-py-revanced).

I hope it answers your query.

**Comment by ramanveerji** [comment]
> > env var
> 
> That's how it is. **MESSAGE_ROOT** and **MESSAGE_NON_ROOT** env [controls](https://github.com/nikhilbadyal/docker-py-revanced/blob/e75e591ba928656adb9b1c1489a84d51a7f38411/.github/workflows/build-apk.yml#L116) what will be sent to the telegram for root & non-root builds respectively.
> 
> This variable(secret) expects a text([Markdown supported](https://www.markdownguide.org/basic-syntax/#links)).
> 
> This is how my secrets look like which is use for [my](https://t.me/revanced_apkss) telegram channel.
> 
> <img alt="Secrets Screenshot" width="1221" src="https://private-user-images.githubusercontent.com/59223300/291051756-5c0c15f3-fdf7-4a58-a773-702d55a6ed13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzI4NTEsIm5iZiI6MTcwMzA3MjU1MSwicGF0aCI6Ii81OTIyMzMwMC8yOTEwNTE3NTYtNWMwYzE1ZjMtZmRmNy00YTU4LWE3NzMtNzAyZDU1YTZlZDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDExNDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MmNmMzBiODExNDVhZGM3M2JhOTBlN2U4NTVmMWUwODg4NmI0NjcxM2E0ZGNjMTUxZDViYWViNTNhNTA1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k5BAdn5uLizyHBGusc6KtsFDZgvjXQtRP6YOHKX1PgM">
> If you want the hyper link to point to the patch resource. You can also add like above. Example for non-root builds -
> 
> ```
> New Release(s) for Non-Root Users🚀\n\n See Changelog [here](https://github.com/inotia00/revanced-patches/releases/latest) and get the apks  [here](https://github.com/nikhilbadyal/docker-py-revanced).
> ```
> 
> I hope it answers your query.
> 
> @ramanveerji

Thanks a lot.

**Comment by ramanveerji** [comment]
> > env var
> 
> That's how it is.  **MESSAGE_ROOT**  and **MESSAGE_NON_ROOT** env [controls](https://github.com/nikhilbadyal/docker-py-revanced/blob/e75e591ba928656adb9b1c1489a84d51a7f38411/.github/workflows/build-apk.yml#L116) what will be sent to the telegram for root & non-root builds respectively.
> 
> This variable(secret) expects a text([Markdown supported](https://www.markdownguide.org/basic-syntax/#links)).
> 
> 
> This is how my secrets look like which is use for [my](https://t.me/revanced_apkss) telegram channel.
> 
> <img width="1221" alt="Secrets Screenshot" src="https://github.com/nikhilbadyal/docker-py-revanced/assets/59223300/5c0c15f3-fdf7-4a58-a773-702d55a6ed13">
> 
> 
> <br>If you want the hyper link to point to the patch resource. You can also add like above. 
> Example for non-root builds - 
> 
> ```
> New Release(s) for Non-Root Users🚀\n\n See Changelog [here](https://github.com/inotia00/revanced-patches/releases/latest) and get the apks  [here](https://github.com/nikhilbadyal/docker-py-revanced).
> ```
> 
> I hope it answers your query.
> 
> 
> @ramanveerji 

Brother is it possible that with every release, it automatically changes the link to that specific patches version as the above way shows only link to latest patches. Is it possible?
