### ISSUE TITLE
The latest version has problems in the history record.It won't record after catching. Texted on tablets and mobile phone

### ISSUE THREAD

**Issue by feiwarm** [nikhilbadyal/docker-py-revanced#430]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

Lovitar 

### Error log or link to the logs if using Github Action

The latest version has problems in the history record.It won't record after catching. Texted on tablets and mobile phone

### ENVS

```Dotenv
Na
```

**Comment by nikhilbadyal** [comment]
> Lovitar

Which app is this ?

**Comment by nikhilbadyal** [comment]
This doesn't look like a builder issue. Probably some bug from resource used(patches) or user is using some adblocker. Hence closing the issue as it's [not a proper place](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support) to raise such issues.
