### ISSUE TITLE
Is there a way to use the pre-release version of patches from ReVanced/revanced-patches/releases

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [nikhilbadyal/docker-py-revanced#434]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Description

Is it possible to use the pre-release version of the revanced patches in the Github action?

### Motivation

Would like to try the pre-release version of the patch.

**Comment by nikhilbadyal** [comment]
Yes, it's possible. Try adding adding patches like this in secrets


`GLOBAL_PATCHES_DL=https://github.com/ReVanced/revanced-patches/releases/tag/v4.0.0-dev.2`
