### ISSUE TITLE
telegram upload problem 

### ISSUE THREAD

**Issue by Pratyay360** [nikhilbadyal/docker-py-revanced#47]
logs
[logs_107.zip](https://github.com/nikhilbadyal/docker-py-revanced/files/9784702/logs_107.zip)

**Comment by nikhilbadyal** [comment]
[Fixed.](https://github.com/nikhilbadyal/ghaction-telegram-uploader/commit/4b70666b659b156c9c3ef5cfa4358bd1bb8438de)

**Comment by Pratyay360** [comment]
@nikhilbadyal can you please share your ``ENVS`` secret

**Comment by nikhilbadyal** [comment]
```
PATCH_APPS=youtube,twitter,reddit,youtube_music
BUILD_EXTENDED=True
EXCLUDE_PATCH_YOUTUBE=custom-branding,enable-debugging
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue,materialyou,custom-branding-decipher3114,custom-branding-name,custom-package-name,always-autorepeat
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music,custom-branding-music-decipher3114,custom-package-name-music,custom-branding-music-red
CHANGELOG_GITHUB_REPOSITORY=inotia00/revanced-patches
```

**Comment by Pratyay360** [comment]
thanks mate

**Comment by Pratyay360** [comment]
BUILD_OG_BRANDING_YOUTUBE=True what will this do

**Comment by nikhilbadyal** [comment]
If enables. It will 2 Youtube. One with the original Icon and the other with Custom Icon.

**Comment by ramanveerji** [comment]
> ```
> PATCH_APPS=youtube,twitter,reddit,youtube_music
> BUILD_EXTENDED=True
> EXCLUDE_PATCH_YOUTUBE=custom-branding,enable-debugging
> EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue,materialyou,custom-branding-decipher3114,custom-branding-name,custom-package-name,always-autorepeat
> EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music,custom-branding-music-decipher3114,custom-package-name-music,custom-branding-music-red
> CHANGELOG_GITHUB_REPOSITORY=inotia00/revanced-patches
> ```





CHANGELOG_GITHUB_REPOSITORY=inotia00/revanced-patches


Is this ENV still working now?
