### ISSUE TITLE
Latest Version of YT & YTM crashing

### ISSUE THREAD

**Issue by SleepDaemon** [nikhilbadyal/docker-py-revanced#5]
The newest release (that came out 13hrs ago at the time of writing this), of YT & YTM crashes. I have confirmed it with few other people that they also facing the same issue. All of us have microG installed, we clear app data and cache, reinstall the apps but still crashing.

Version in question: https://github.com/nikhilbadyal/docker-py-revanced/releases/tag/Build-2022.08.29-23.56.27

**Comment by nikhilbadyal** [comment]
Actually, the versions I build in the GitHub release aren't the official recommended versions.  I always build beta versions. That might be the reason for the crash. I triggered a rebuild with recommended version. You can now download it from the release section now and will work fine.

https://github.com/nikhilbadyal/docker-py-revanced/releases/latest

**Comment by Lostvale0** [comment]
So only if I add the value **latest** in my github secret called **ENV** then I'll be getting beta builds right?

**Comment by Lostvale0** [comment]
Thanks again!

**Comment by nikhilbadyal** [comment]
@Lostvale0 Yes it's very possible to do. At how much time interval to want automated builds ? Daily , twice a day or anything else ?

**Comment by Lostvale0** [comment]
@nikhilbadyal Daily

**Comment by nikhilbadyal** [comment]
Add 
```
  schedule:
    - cron: "0 0 * * *"
```

in .github/workflowa/buildapk.yml

In final it should look like this

<img width="532" alt="image" src="https://user-images.githubusercontent.com/59223300/187832537-c51347af-266d-4a83-895d-244bb997e9e4.png">

**Comment by Lostvale0** [comment]
Cool added it, will this auto delete previous builds too?

**Comment by nikhilbadyal** [comment]
No, It'll just build APKS daily. 

You can use [this](https://github.com/marketplace/actions/delete-older-releases) to delete builds.

**Comment by Lostvale0** [comment]
So I'll need to create an another yml file for that right? I can't add it in buildapk.yml right

**Comment by nikhilbadyal** [comment]
You can add it to the same file. Just make sure to run `delete` before building APKS. By that I mean, that deleting the build should be the first step.

**Comment by Lostvale0** [comment]
Ahh thanks for the image, fixed my confusion 👍

**Comment by Lostvale0** [comment]
![image](https://user-images.githubusercontent.com/94958746/187869190-594a06e9-ce6c-42f6-89cc-0ba2ae48434b.png)
Im confused what value I should put in delete_tag_pattern, I keep getting this error 
![image](https://user-images.githubusercontent.com/94958746/187869423-8f34708c-92ad-44a7-a2e0-535e7d8e9b46.png)

**Comment by nikhilbadyal** [comment]
Great, it worked. I saw you updated the tag name. With the existing configuration, you could have added `Build*`.

**Comment by Lostvale0** [comment]
Thanks for the tip! Yeah recommended releases only would be better.
