### ISSUE TITLE
auto release bug

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#510]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

none

### Error log or link to the logs if using Github Action

No error

### ENVS

```Dotenv
EXTRA_FILES=https://github.com/ReVanced/GmsCore/releases/latest@MicroG.apk
```

### Additional info

There is a problem since microg has been released in 2 variants, the builder thinks there is an update and auto builds every 1 hour and pushes revanced microg to the release section. Is there any way we can get both the releases at once and there is no auto building every 1 hour. Check this https://github.com/ReVanced/GmsCore/releases/tag/v0.3.1.4.240913 as it is having 2 releases.

**Comment by nikhilbadyal** [comment]
Share complete envs.

**Comment by ramanveerji** [comment]
> Share complete envs.

It is issue because of 2 releases in gmscore repo. Please check that.

**Comment by nikhilbadyal** [comment]
> It is issue because of 2 releases in gmscore repo

That's not how it works. The fields are required in the issue for a reason. They help me in debugging.

**Comment by ramanveerji** [comment]
> > It is issue because of 2 releases in gmscore repo
> 
> That's not how it works. The fields are required in the issue for a reason. They help me in debugging.

Bro try adding extra_files var same and see it will keep on building after every hour

**Comment by IMXEren** [comment]
`docker-py-revanced` is the OG and still doesn't face build repititions. @ramanveerji, you should simply paste whole envs in the issue fields. I asked you to do this before...and I can't figure what's the issue in pasting it complete. The maintainer takes out his precious time to develop and not to dig around the bugs if they exist.

**Comment by ramanveerji** [comment]
> `docker-py-revanced` is the OG and still doesn't face build repititions. @ramanveerji, you should simply paste whole envs in the issue fields. I asked you to do this before...and I can't figure what's the issue in pasting it complete. The maintainer takes out his precious time to develop and not to dig around the bugs if they exist.

I know brother but the issue is not in other envs. They work fine. Only issue is in extra_files section, that's why I shared that only. You can add the same and check.

**Comment by nikhilbadyal** [comment]
Thank you for reaching out.However, it seems that the information provided is incomplete, particularly regarding the `ENVS` section.Unfortunately, given the the lack of details. We are unable to proceed with further investigation at this time. 

If you encounter any further issues or have additional information to provide in the future, please don't hesitate to open a new issue **providing** all the **necessary** info, and we'll do our best to assist.

Note - Contributors are not here to dig around others repository and find out what went wrong.
