### ISSUE TITLE
"GITHUB_REPOSITORY" not set

### ISSUE THREAD

**Issue by TechMorgan** [nikhilbadyal/docker-py-revanced#511]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

Youtube

### Error log or link to the logs if using Github Action

Traceback (most recent call last):
  File "C:\Users\Deepak\Desktop\docker-py-revanced-main\main.py", line 63, in <module>
    main()
  File "C:\Users\Deepak\Desktop\docker-py-revanced-main\main.py", line 34, in main
    updates_info = load_older_updates(env)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Deepak\Desktop\docker-py-revanced-main\src\utils.py", line 252, in load_older_updates
    github_repository=env.str("GITHUB_REPOSITORY"),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Deepak\Desktop\docker-py-revanced-main\venv\Lib\site-packages\environs\__init__.py", line 116, in method
    raise EnvError(
environs.EnvError: Environment variable "GITHUB_REPOSITORY" not set

### ENVS

```Dotenv
#Global:
EXTRA_FILES=https://github.com/ReVanced/GmsCore/releases/latest@Revanced-Microg.apk
PATCH_APPS=youtube
GLOBAL_CLI_DL=https://github.com/revanced/revanced-cli/releases/latest-prerelease
GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches/releases/latest-prerelease
GLOBAL_INTEGRATIONS_DL=https://github.com/revanced/revanced-integrations/releases/latest-prerelease

#YouTube:
YOUTUBE_PATCHES_DL=https://github.com/rufusin/revanced-patches/releases/latest-prerelease
YOUTUBE_INTEGRATIONS_DL=https://github.com/rufusin/revanced-integrations/releases/latest-prerelease
YOUTUBE_EXCLUDE_PATCH=custom-branding-icon-youtube,custom-branding-name-youtube,enable-debug-logging,hide-fullscreen-button,shorts-overlay-buttons,hide-shorts-components
```

**Comment by nikhilbadyal** [comment]
Are you building locally ?. If yes there is no way to automatically know the GitHub Repository where builder is located. You can put `GITHUB_REPOSITORY` manually in [.env](https://github.com/nikhilbadyal/docker-py-revanced/blob/main/.env) file.

**Comment by TechMorgan** [comment]
GITHUB_REPOSITORY=https://github.com/nikhilbadyal/docker-py-revanced
Like this?

**Comment by nikhilbadyal** [comment]
> GITHUB_REPOSITORY=https://github.com/nikhilbadyal/docker-py-revanced
> Like this?

GITHUB_REPOSITORY=nikhilbadyal/docker-py-revanced

This should do the job. But why are you running the auto builder. You can just use

`python main.py`

**Comment by TechMorgan** [comment]
> `GITHUB_REPOSITORY=nikhilbadyal/docker-py-revanced`
> 
> This should do the job. But why are you running the auto builder.
> 
> You can just use `python main.py`

Yeah i do use `python main.py`

**Comment by TechMorgan** [comment]
I'm rate-limited now

> > `GITHUB_REPOSITORY=nikhilbadyal/docker-py-revanced`
> > This should do the job. But why are you running the auto builder.
> > You can just use `python main.py`
> 
> Yeah i do use `python main.py`

**Comment by nikhilbadyal** [comment]
> I'm rate-limited now

You can provide GitHub token. See [here](https://github.com/nikhilbadyal/docker-py-revanced?tab=readme-ov-file#personal-access-token)

**Comment by nikhilbadyal** [comment]
I have also added a fix in the attached PR. From now on the builder will not fail even when env is not set.
