### ISSUE TITLE
Add used patches version

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#528]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Description

Right now if we use the builder and output the apps on telegram it gives all apps perfectly. But it doesn't add any information about the patches version used. Like it should send the text "Based on ReVanced patches version x.x.x" and then send all apps. This way one can see what version of patches are used in building the apps. 

### Motivation

It can help the person who is building for himself to keep a check on the version of patches used to build and release the apps in his telegram channel.

**Comment by nikhilbadyal** [comment]
Is [this](https://github.com/nikhilbadyal/docker-py-revanced/issues/413#issuecomment-1859078582) not sufficient ?

**Comment by ramanveerji** [comment]
Lets suppose we use this. Then after some weeks when you go back to your channel to see what builds are made from what patch version you will always see the latest as the link will show latest version only. But if there is some text that shows the version of patch then it will be good. One can see ok this build is from version 1.0.0. That one is from version 2.0.0. It will help the person in determining the patch version.

**Comment by nikhilbadyal** [comment]
Filename now contains Patch Version. Also the release will have few meta data files which contains much more information. 

<img width="1253" alt="image" src="https://github.com/user-attachments/assets/dfdfe10d-c23b-42ab-9350-666dd6a6d147" />

**Comment by ramanveerji** [comment]
bro add code so these files changelog.md, changelog.json, updates.json don't get added in releases section. the patch version in app name is sufficient
https://github.com/nikhilbadyal/docker-py-revanced/releases

**Comment by nikhilbadyal** [comment]
What's issue are you facing with these file being present in the release?

**Comment by ramanveerji** [comment]
> What's issue are you facing with these file being present in the release?

These are unnecessary as these also get uploaded to telegram. The revanced patch version is already added in file name it is fine.
