### ISSUE TITLE
virus total scan not working

### ISSUE THREAD

**Issue by Pratyay360** [nikhilbadyal/docker-py-revanced#57]
LOGS 
[logs_131.zip](https://github.com/nikhilbadyal/docker-py-revanced/files/9830826/logs_131.zip)

**Comment by nikhilbadyal** [comment]
Might be some GitHub issue. As its working [fine](https://github.com/nikhilbadyal/docker-py-revanced/actions/runs/3290273129/jobs/5422890680) for me.
