### ISSUE TITLE
Revanced Cli v5 Support

### ISSUE THREAD

**Issue by phamleduy04** [nikhilbadyal/docker-py-revanced#572]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

everything

### Error log or link to the logs if using Github Action

https://github.com/phamleduy04/docker-py-revanced/actions/runs/11786395711/job/32829594678

### ENVS

```Dotenv
PATCH_APPS=youtube,youtube_music,photos,tiktok
EXCLUDE_PATCH_YOUTUBE=custom-branding,enable-debugging
EXCLUDE_PATCH_YOUTUBE_MUSIC=custom-branding-music
PERSONAL_ACCESS_TOKEN=<redacted>
EXTRA_FILES=https://github.com/ReVanced/GmsCore/releases/latest@app.revanced.android.gms-240913008-signed.apk
```

### Additional info

Just happened today, the code run few days ago without any issues

**Comment by Xyaren** [comment]
Version 5 Of the CLI is released an the "integrations" repository was merged into the "patches" repository (is no longer needed separately).
I guess this is related.

**Comment by FallenLeave91** [comment]
I also have this issue as you can see here https://github.com/FallenLeave91/docker-py-revanced/actions/runs/11798563671/job/32865014613#step:9:195

ENVS
```
PATCH_APPS=youtube
```

**Comment by nikhilbadyal** [comment]
Thanks for reporting the guys. Special thanks to @Xyaren for pointing me in right direction. The issue is fixed now.
