### ISSUE TITLE
unable to build apks

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#575]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

all

### Error log or link to the logs if using Github Action

Run if [[ "false" =~ ^(true|True|1)$ ]]; then
Using Prod compose file.
 revanced Pulling 
 04e7578caeaa Pulling fs layer 
 97413375e23b Pulling fs layer 
 f3d6785c9be8 Pulling fs layer 
 ad4c793cdc66 Pulling fs layer 
 6269fbb18f76 Pulling fs layer 
 ad4c793cdc66 Waiting 
 43f60f73802c Pulling fs layer 
 43251eec666f Pulling fs layer 
 164408a371f3 Pulling fs layer 
 6269fbb18f76 Waiting 
 8c59fb5f28c1 Pulling fs layer 
 01684a6f3e8c Pulling fs layer 
 43f60f73802c Waiting 
 43251eec666f Waiting 
 1c5a2d8c25c3 Pulling fs layer 
 5c1ceecd8afe Pulling fs layer 
 164408a371f3 Waiting 
 01684a6f3e8c Waiting 
 8c59fb5f28c1 Waiting 
 5c1ceecd8afe Waiting 
 1c5a2d8c25c3 Waiting 
 97413375e23b Downloading [>                                                  ]  11.67kB/1.077MB
 f3d6785c9be8 Downloading [>                                                  ]  115.2kB/11.22MB
 04e7578caeaa Downloading [>                                                  ]  325.9kB/31.43MB
 97413375e23b Verifying Checksum 
 97413375e23b Download complete 
 f3d6785c9be8 Verifying Checksum 
 f3d6785c9be8 Download complete 
 ad4c793cdc66 Downloading [==================================================>]     243B/243B
 ad4c793cdc66 Verifying Checksum 
 ad4c793cdc66 Download complete 
 04e7578caeaa Downloading [======================>                            ]  13.93MB/31.43MB
 6269fbb18f76 Downloading [>                                                  ]   30.7kB/2.992MB
 6269fbb18f76 Verifying Checksum 
 6269fbb18f76 Download complete 
 04e7578caeaa Verifying Checksum 
 04e7578caeaa Download complete 
 04e7578caeaa Extracting [>                                                  ]  327.7kB/31.43MB
 43f60f73802c Downloading [==================================================>]      93B/93B
 43f60f73802c Verifying Checksum 
 43f60f73802c Download complete 
 164408a371f3 Downloading [==================================================>]     3[19](https://github.com/ramanveerji/docker-py-revanced/actions/runs/11806404622/job/32890937183#step:9:20)B/319B
 164408a371f3 Verifying Checksum 
 164408a371f3 Download complete 
 43251eec666f Downloading [>                                                  ]  539.9kB/179.5MB
 04e7578caeaa Extracting [=======>                                           ]  4.588MB/31.43MB
 8c59fb5f28c1 Downloading [>                                                  ]  147.2kB/14.32MB
 01684a6f3e8c Downloading [==================================================>]     158B/158B
 01684a6f3e8c Verifying Checksum 
 01684a6f3e8c Download complete 
 8c59fb5f28c1 Downloading [==================================================>]  14.32MB/14.32MB
 8c59fb5f28c1 Download complete 
 43251eec666f Downloading [==>                                                ]  10.18MB/179.5MB
 04e7578caeaa Extracting [==============>                                    ]  9.175MB/31.43MB
 5c1ceecd8afe Downloading [=>                                                 ]  1.369kB/56.79kB
 1c5a2d8c25c3 Downloading [==================================================>]     159B/159B
 1c5a2d8c25c3 Verifying Checksum 
 1c5a2d8c25c3 Download complete 
 5c1ceecd8afe Downloading [==================================================>]  56.79kB/56.79kB
 5c1ceecd8afe Verifying Checksum 
 5c1ceecd8afe Download complete 
 43251eec666f Downloading [========>                                          ]  29.42MB/179.5MB
 04e7578caeaa Extracting [======================>                            ]  14.42MB/31.43MB
 43251eec666f Downloading [============>                                      ]  43.83MB/179.5MB
 04e7578caeaa Extracting [===========================>                       ]  17.37MB/31.43MB
 43251eec666f Downloading [===============>                                   ]  57.23MB/179.5MB
 04e7578caeaa Extracting [========================================>          ]  25.56MB/31.43MB
 43251eec666f Downloading [===================>                               ]   71.6MB/179.5MB
 04e7578caeaa Extracting [=============================================>     ]  28.84MB/31.43MB
 43251eec666f Downloading [======================>                            ]  81.21MB/179.5MB
 43251eec666f Downloading [=========================>                         ]  89.76MB/179.5MB
 04e7578caeaa Extracting [===============================================>   ]  30.15MB/31.43MB
 43251eec666f Downloading [=============================>                     ]  104.2MB/179.5MB
 43251eec666f Downloading [================================>                  ]  115.4MB/179.5MB
 04e7578caeaa Extracting [================================================>  ]  30.47MB/31.43MB
 43251eec666f Downloading [===================================>               ]  127.7MB/179.5MB
 43251eec666f Downloading [========================================>          ]  144.8MB/179.5MB
 04e7578caeaa Extracting [==================================================>]  31.43MB/31.43MB
 04e7578caeaa Pull complete 
 97413375e23b Extracting [=>                                                 ]  32.77kB/1.077MB
 43251eec666f Downloading [===========================================>       ]    156MB/179.5MB
 97413375e23b Extracting [==================================================>]  1.077MB/1.077MB
 97413375e23b Extracting [==================================================>]  1.077MB/1.077MB
 43251eec666f Downloading [==============================================>    ]  167.8MB/179.5MB
 43251eec666f Downloading [=================================================> ]    178MB/179.5MB
 43251eec666f Verifying Checksum 
 43251eec666f Download complete 
 97413375e23b Pull complete 
 f3d6785c9be8 Extracting [>                                                  ]  131.1kB/11.22MB
 f3d6785c9be8 Extracting [================>                                  ]   3.67MB/11.22MB
 f3d6785c9be8 Extracting [==============================>                    ]  6.947MB/11.22MB
 f3d6785c9be8 Extracting [===========================================>       ]  9.699MB/11.22MB
 f3d6785c9be8 Extracting [==================================================>]  11.22MB/11.22MB
 f3d6785c9be8 Pull complete 
 ad4c793cdc66 Extracting [==================================================>]     243B/243B
 ad4c793cdc66 Extracting [==================================================>]     243B/243B
 ad4c793cdc66 Pull complete 
 6269fbb18f76 Extracting [>                                                  ]  32.77kB/2.992MB
 6269fbb18f76 Extracting [=========================>                         ]   1.54MB/2.992MB
 6269fbb18f76 Extracting [==========================================>        ]  2.556MB/2.992MB
 6269fbb18f76 Extracting [==================================================>]  2.992MB/2.992MB
 6269fbb18f76 Pull complete 
 43f60f73802c Extracting [==================================================>]      93B/93B
 43f60f73802c Extracting [==================================================>]      93B/93B
 43f60f73802c Pull complete 
 43251eec666f Extracting [>                                                  ]  557.1kB/179.5MB
 43251eec666f Extracting [==>                                                ]  8.356MB/179.5MB
 43251eec666f Extracting [=====>                                             ]  18.94MB/179.5MB
 43251eec666f Extracting [===========>                                       ]  41.22MB/179.5MB
 43251eec666f Extracting [=================>                                 ]  62.39MB/179.5MB
 43251eec666f Extracting [=======================>                           ]  83.56MB/179.5MB
 43251eec666f Extracting [==========================>                        ]  93.59MB/179.5MB
 43251eec666f Extracting [============================>                      ]  102.5MB/179.5MB
 43251eec666f Extracting [===============================>                   ]    112MB/179.5MB
 43251eec666f Extracting [=================================>                 ]  1[20](https://github.com/ramanveerji/docker-py-revanced/actions/runs/11806404622/job/32890937183#step:9:21).9MB/179.5MB
 43251eec666f Extracting [===================================>               ]  128.7MB/179.5MB
 43251eec666f Extracting [======================================>            ]  136.5MB/179.5MB
 43251eec666f Extracting [========================================>          ]  143.7MB/179.5MB
 43251eec666f Extracting [==========================================>        ]  151.5MB/179.5MB
 43251eec666f Extracting [============================================>      ]  158.8MB/179.5MB
 43251eec666f Extracting [=============================================>     ]  163.8MB/179.5MB
 43251eec666f Extracting [==============================================>    ]  167.7MB/179.5MB
 43251eec666f Extracting [===============================================>   ]  171.6MB/179.5MB
 43251eec666f Extracting [================================================>  ]  174.4MB/179.5MB
 43251eec666f Extracting [=================================================> ]  176.6MB/179.5MB
 43251eec666f Extracting [=================================================> ]  178.8MB/179.5MB
 43251eec666f Extracting [==================================================>]  179.5MB/179.5MB
 43251eec666f Pull complete 
 164408a371f3 Extracting [==================================================>]     319B/319B
 164408a371f3 Extracting [==================================================>]     319B/319B
 164408a371f3 Pull complete 
 8c59fb5f28c1 Extracting [>                                                  ]  163.8kB/14.32MB
 8c59fb5f28c1 Extracting [=========>                                         ]  2.6[21](https://github.com/ramanveerji/docker-py-revanced/actions/runs/11806404622/job/32890937183#step:9:22)MB/14.32MB
 8c59fb5f28c1 Extracting [===============>                                   ]  4.424MB/14.32MB
 8c59fb5f28c1 Extracting [====================>                              ]  5.898MB/14.32MB
 8c59fb5f28c1 Extracting [===========================>                       ]  7.864MB/14.32MB
 8c59fb5f28c1 Extracting [=============================>                     ]   8.52MB/14.32MB
 8c59fb5f28c1 Extracting [=================================>                 ]  9.503MB/14.32MB
 8c59fb5f28c1 Extracting [===================================>               ]  10.16MB/14.32MB
 8c59fb5f28c1 Extracting [==================================================>]  14.32MB/14.32MB
 8c59fb5f28c1 Pull complete 
 01684a6f3e8c Extracting [==================================================>]     158B/158B
 01684a6f3e8c Extracting [==================================================>]     158B/158B
 01684a6f3e8c Pull complete 
 1c5a2d8c25c3 Extracting [==================================================>]     159B/159B
 1c5a2d8c25c3 Extracting [==================================================>]     159B/159B
 1c5a2d8c25c3 Pull complete 
 5c1ceecd8afe Extracting [============================>                      ]  32.77kB/56.79kB
 5c1ceecd8afe Extracting [==================================================>]  56.79kB/56.79kB
 5c1ceecd8afe Pull complete 
 revanced Pulled 
 Network docker-py-revanced_default  Creating
 Network docker-py-revanced_default  Created
 Container revanced-builder  Creating
 Container revanced-builder  Created
Attaching to revanced-builder
revanced-builder  | 2024-11-12 21:57:31.997 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found app.revanced.android.gms-240913008-hw-signed.apk to be downloaded from https://github.com/ReVanced/GmsCore/releases/download/v0.3.1.4.240913/app.revanced.android.gms-240913008-hw-signed.apk
revanced-builder  | 2024-11-12 21:57:31.998 | INFO     | src.downloader.download:_download:35 - Trying to download ReVancedMicroG-output.apk from https://github.com/ReVanced/GmsCore/releases/download/v0.3.1.4.240913/app.revanced.android.gms-240913008-hw-signed.apk
revanced-builder  | 2024-11-12 21:57:31.998 | DEBUG    | src.downloader.download:_download:40 - Using personal access token
revanced-builder  | 
ReVancedMicroG-output.apk:   0%|          | 0.00/37.9M [00:00<?, ?iB/s]
ReVancedMicroG-output.apk:  79%|███████▉  | 30.0M/37.9M [00:00<00:00, 235MiB/s]
ReVancedMicroG-output.apk: 100%|██████████| 37.9M/37.9M [00:00<00:00, 246MiB/s]
revanced-builder  | 2024-11-12 21:57:32.305 | DEBUG    | src.downloader.download:_download:62 - Downloaded ReVancedMicroG-output.apk
revanced-builder  | 2024-11-12 21:57:32.384 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found APKEditor-1.4.1.jar to be downloaded from https://github.com/REAndroid/APKEditor/releases/download/V1.4.1/APKEditor-1.4.1.jar
revanced-builder  | 2024-11-12 21:57:32.385 | INFO     | src.downloader.download:_download:35 - Trying to download apkeditor-output.jar from https://github.com/REAndroid/APKEditor/releases/download/V1.4.1/APKEditor-1.4.1.jar
revanced-builder  | 2024-11-12 21:57:32.385 | DEBUG    | src.downloader.download:_download:40 - Using personal access token
revanced-builder  | 
apkeditor-output.jar:   0%|          | 0.00/6.80M [00:00<?, ?iB/s]
apkeditor-output.jar: 100%|██████████| 6.80M/6.80M [00:00<00:00, 113MiB/s]
revanced-builder  | 2024-11-12 21:57:32.533 | DEBUG    | src.downloader.download:_download:62 - Downloaded apkeditor-output.jar
revanced-builder  | 2024-11-12 21:57:32.558 | DEBUG    | src.utils:check_java:209 - Cool!! Java is available
revanced-builder  | 2024-11-12 21:57:32.660 | INFO     | __main__:main:36 - Will Patch only ['youtube', 'youtube_music', 'inshorts', 'twitter', 'photos']
revanced-builder  | 2024-11-12 21:57:32.660 | INFO     | __main__:main:38 - Trying to build youtube
revanced-builder  | 2024-11-12 21:57:32.661 | INFO     | src.app:download_patch_resources:147 - Downloading resources for patching.
revanced-builder  | 2024-11-12 21:57:32.796 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found revanced-cli-5.0.0-all.jar to be downloaded from https://github.com/ReVanced/revanced-cli/releases/download/v5.0.0/revanced-cli-5.0.0-all.jar
revanced-builder  | 2024-11-12 21:57:32.797 | INFO     | src.downloader.download:_download:35 - Trying to download df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar from https://github.com/ReVanced/revanced-cli/releases/download/v5.0.0/revanced-cli-5.0.0-all.jar
revanced-builder  | 2024-11-12 21:57:32.797 | DEBUG    | src.downloader.download:_download:40 - Using personal access token
revanced-builder  | 
df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar:   0%|          | 0.00/49.4M [00:00<?, ?iB/s]
df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar:  61%|██████    | 30.0M/49.4M [00:00<00:00, 286MiB/s]
df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar: 100%|██████████| 49.4M/49.4M [00:00<00:00, 267MiB/s]
revanced-builder  | 2024-11-12 21:57:33.074 | DEBUG    | src.downloader.download:_download:62 - Downloaded df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar
revanced-builder  | 2024-11-12 21:57:33.190 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found patches-5.0.2.rvp to be downloaded from https://github.com/ReVanced/revanced-patches/releases/download/v5.0.2/patches-5.0.2.rvp
revanced-builder  | 2024-11-12 21:57:33.191 | INFO     | src.downloader.download:_download:35 - Trying to download 303ca8188fdfb65e[22](https://github.com/ramanveerji/docker-py-revanced/actions/runs/11806404622/job/32890937183#step:9:23)06ddc659d8026c18e5dc72ce0da24d8c4ebf56c5faba37.rvp from https://github.com/ReVanced/revanced-patches/releases/download/v5.0.2/patches-5.0.2.rvp
revanced-builder  | 2024-11-12 21:57:33.191 | DEBUG    | src.downloader.download:_download:40 - Using personal access token
revanced-builder  | 
303ca8188fdfb65e2206ddc659d8026c18e5dc72ce0da24d8c4ebf56c5faba37.rvp:   0%|          | 0.00/4.83M [00:00<?, ?iB/s]
303ca8188fdfb65e2206ddc659d8026c18e5dc72ce0da24d8c4ebf56c5faba37.rvp: 100%|██████████| 4.83M/4.83M [00:00<00:00, 276MiB/s]
revanced-builder  | 2024-11-12 21:57:33.295 | DEBUG    | src.downloader.download:_download:62 - Downloaded 303ca8188fdfb65e2206ddc659d8026c18e5dc72ce0da24d8c4ebf56c5faba37.rvp
revanced-builder  | 2024-11-12 21:57:33.399 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found patches-5.0.2.rvp to be downloaded from https://github.com/ReVanced/revanced-patches/releases/download/v5.0.2/patches-5.0.2.rvp
revanced-builder  | 2024-11-12 21:57:33.399 | DEBUG    | src.downloader.download:_download:33 - Skipping download of 303ca8188fdfb65e2206ddc659d8026c18e5dc72ce0da24d8c4ebf56c5faba37.rvp from https://github.com/ReVanced/revanced-patches/releases/download/v5.0.2/patches-5.0.2.rvp. File already exists or dry running.
revanced-builder  | Traceback (most recent call last):
revanced-builder  |   File "/app/main.py", line 63, in <module>
revanced-builder  |     main()
revanced-builder  |   File "/app/main.py", line 42, in main
revanced-builder  |     patcher = Patches(config, app)
revanced-builder  |               ^^^^^^^^^^^^^^^^^^^^
revanced-builder  |   File "/app/src/patches.py", line 143, in __init__
revanced-builder  |     self.fetch_patches(config, app)
revanced-builder  |   File "/app/src/patches.py", line 1[23](https://github.com/ramanveerji/docker-py-revanced/actions/runs/11806404622/job/32890937183#step:9:24), in fetch_patches
revanced-builder  |     patches = patch_loader.load_patches(f"{config.temp_folder}/{patches_file}")
revanced-builder  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
revanced-builder  |   File "/app/src/patches.py", line 216, in load_patches
revanced-builder  |     return json.load(f)
revanced-builder  |            ^^^^^^^^^^^^
revanced-builder  |   File "/usr/local/lib/python3.12/json/__init__.py", line [29](https://github.com/ramanveerji/docker-py-revanced/actions/runs/11806404622/job/32890937183#step:9:30)3, in load
revanced-builder  |     return loads(fp.read(),
revanced-builder  |                  ^^^^^^^^^
revanced-builder  |   File "<frozen codecs>", line [32](https://github.com/ramanveerji/docker-py-revanced/actions/runs/11806404622/job/32890937183#step:9:33)2, in decode
revanced-builder  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 10: invalid start byte

revanced-builder exited with code 1

### ENVS

```Dotenv
#Global ENVS
PATCH_APPS=youtube,youtube_music
GLOBAL_KEYSTORE_FILE_NAME=rs.keystore
GLOBAL_CLI_DL=https://github.com/revanced/revanced-cli
GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches
GLOBAL_PATCHES_JSON_DL=https://github.com/revanced/revanced-patches
GLOBAL_ARCHS_TO_BUILD=arm64-v8a
GLOBAL_SPACE_FORMATTED_PATCHES=true
CHANGELOG_GITHUB_REPOSITORY=ReVanced/revanced-patches

#Youtube
YOUTUBE_EXCLUDE_PATCH=custom-branding,change-header
YOUTUBE_ARCHS_TO_BUILD=arm64-v8a,armeabi-v7a

#Extra Files
EXTRA_FILES=https://github.com/ReVanced/GmsCore/releases/latest@ReVancedMicroG.apk
```

**Comment by nikhilbadyal** [comment]
With new revanced CLI. Patches.json is not provided anymore. So don't supply 
`GLOBAL_PATCHES_JSON_DL=https://github.com/revanced/revanced-patches`. Check [my](https://github.com/nikhilbadyal/docker-py-revanced/blob/main/.env.my) envs for example.

**Comment by ramanveerji** [comment]
> With new revanced CLI. Patches.json is not provided anymore. So don't supply 
> `GLOBAL_PATCHES_JSON_DL=https://github.com/revanced/revanced-patches`. Check [my](https://github.com/nikhilbadyal/docker-py-revanced/blob/main/.env.my) envs for example. 

Ok please update the readme file also
