### ISSUE TITLE
Incompatible with older Revanced CLI v4

### ISSUE THREAD

**Issue by jackblk** [nikhilbadyal/docker-py-revanced#581]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

Youtube

### Error log or link to the logs if using Github Action

Hit this error when running for `python check_resource_updates.py`

```
src.exceptions.PatchingFailedError: Failed to download resource.
```

### ENVS

```Dotenv
YOUTUBE_CLI_DL=https://github.com/inotia00/revanced-cli
YOUTUBE_PATCHES_DL=https://github.com/inotia00/revanced-patches
YOUTUBE_PATCHES_JSON_DL=https://github.com/inotia00/revanced-patches
YOUTUBE_INTEGRATIONS_DL=https://github.com/inotia00/revanced-integrations
```

### Additional info

I pulled the code and did some debugging.  `python check_resource_updates.py` hits the exception while trying to download [`("patches", self.patches_dl, config, ".*rvp"),`](https://github.com/nikhilbadyal/docker-py-revanced/blob/c4f8d1160fdb6394ebf430d1cae4e7a3fe26ac76/src/app.py#L151C12-L151C59)

https://github.com/inotia00/revanced-cli is still on v4, https://github.com/inotia00/revanced-patches still has `patches.json` and no `.*rvp` yet so the patch download URL is empty.

Is there a way to support inotia00 patches in this builder? For now I will revert back to commit 3e3d14c14a31c641c46331a960083e7c93c7bb8a, it should still work with v4.

**Comment by nikhilbadyal** [comment]
Hey @jackblk, you're correct that v4 support has been dropped. I hope [inotia00](https://github.com/inotia00/revanced-cli) and other forks will update their code soon. However, if they decide not to update to v5, I might consider supporting both v4 and v5. For now, I'll proceed under the assumption that they'll adapt to v5.

As you've probably guessed, you can roll back to [this commit](https://github.com/nikhilbadyal/docker-py-revanced/commit/3e3d14c14a31c641c46331a960083e7c93c7bb8a) if you need v4 support again.


I'll keep this issue open for time being.

**Comment by EatPrilosec** [comment]
thought id share how to make a v4 branch from github's web ui

1) go to http://github.com/<your>/<fork>/tree/3e3d14c14a31c641c46331a960083e7c93c7bb8a

2) click `3e3d14c` branch drop down menu

3) type new branch name like `v4`  in drop down menu's search box 

4) click `Create branch v4 from 3e3d14c` 

now you can run actions using v4 branch until the devs upgrade to v5

**Comment by Fred-Vatin** [comment]
I still have the same error with this `3e3d14c` as you can see [here](https://github.com/Fred-Vatin/docker-py-revanced/actions/workflows/build-apk.yml). Line 221:
```
revanced-builder  | 2024-11-26 19:12:35.004 | ERROR    | __main__:main:55 - Failed to download resource.
```

My ENVS:
```
#Global:
PERSONAL_ACCESS_TOKEN=***
EXTRA_FILES=https://github.com/ReVanced/GmsCore/releases/latest@Revanced-Microg.apk,https://github.com/inotia00/mMicroG/releases/latest@mmicrog.apk
PATCH_APPS=youtube,youtube_music
GLOBAL_CLI_DL=https://github.com/inotia00/revanced-cli
GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches
GLOBAL_PATCHES_JSON_DL=https://github.com/inotia00/revanced-patches

#YouTube:
YOUTUBE_EXCLUDE_PATCH=custom-branding-icon-revancify-blue,custom-branding-icon-revancify-red,custom-branding-icon-mmt,custom-branding-youtube-name,enable-debug-logging

#YouTube Music:
YOUTUBE_MUSIC_EXCLUDE_PATCH=custom-branding-icon-mmt,custom-branding-icon-revancify-blue,custom-branding-icon-revancify-red,custom-branding-music-name,enable-compact-dialog,enable-debug-logging
```

What ENVS do you use ?

**Comment by EatPrilosec** [comment]
> I still have the same error with this `3e3d14c` as you can see [here](https://github.com/Fred-Vatin/docker-py-
> What ENVS do you use ?

i had to change apk sources:

https://github.com/EatPrilosec/docker-py-revanced/blob/f9381aaedf850aa6cc872877dddc0a64e34539ee/.env

**Comment by jackblk** [comment]
V5 released, closing https://github.com/inotia00/revanced-patches/releases/tag/v5.0.2
