### ISSUE TITLE
not downloading latest twitter version

### ISSUE THREAD

**Issue by ramanveerji** [nikhilbadyal/docker-py-revanced#597]
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

twitter

### Error log or link to the logs if using Github Action

revanced-builder  | 2024-12-05 10:32:31.200 | INFO     | __main__:main:38 - Trying to build twitter
revanced-builder  | 2024-12-05 10:32:31.200 | INFO     | src.app:download_patch_resources:147 - Downloading resources for patching.
revanced-builder  | 2024-12-05 10:32:31.368 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found revanced-cli-5.0.0-all.jar to be downloaded from https://github.com/ReVanced/revanced-cli/releases/download/v5.0.0/revanced-cli-5.0.0-all.jar
revanced-builder  | 2024-12-05 10:32:31.368 | INFO     | src.downloader.download:_download:35 - Trying to download df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar from https://github.com/ReVanced/revanced-cli/releases/download/v5.0.0/revanced-cli-5.0.0-all.jar
revanced-builder  | 2024-12-05 10:32:31.368 | DEBUG    | src.downloader.download:_download:40 - Using personal access token
revanced-builder  | 
df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar:   0%|          | 0.00/49.4M [00:00<?, ?iB/s]
df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar:  61%|██████    | 30.0M/49.4M [00:00<00:00, 294MiB/s]
df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar: 100%|██████████| 49.4M/49.4M [00:00<00:00, 308MiB/s]
revanced-builder  | 2024-12-05 10:32:31.727 | DEBUG    | src.downloader.download:_download:62 - Downloaded df5f3e56a9720b24faf3ffc148589ecdc1c8935baa61e1d00b07c8db2bd2c98d.jar
revanced-builder  | 2024-12-05 10:32:31.873 | DEBUG    | src.downloader.github:_get_release_assets:97 - Found patches-5.2.1.rvp to be downloaded from https://github.com/ReVanced/revanced-patches/releases/download/v5.2.1/patches-5.2.1.rvp
revanced-builder  | 2024-12-05 10:32:31.874 | INFO     | src.downloader.download:_download:35 - Trying to download c121e3a5e0d3e550b7ff0b4e8d0921f6e9697ef8e91e9197b35b913c633e0ef1.rvp from https://github.com/ReVanced/revanced-patches/releases/download/v5.2.1/patches-5.2.1.rvp
revanced-builder  | 2024-12-05 10:32:31.874 | DEBUG    | src.downloader.download:_download:40 - Using personal access token
revanced-builder  | 
c121e3a5e0d3e550b7ff0b4e8d0921f6e9697ef8e91e9197b35b913c633e0ef1.rvp:   0%|          | 0.00/4.85M [00:00<?, ?iB/s]
c121e3a5e0d3e550b7ff0b4e8d0921f6e9697ef8e91e9197b35b913c633e0ef1.rvp: 100%|██████████| 4.85M/4.85M [00:00<00:00, 286MiB/s]
revanced-builder  | 2024-12-05 10:32:32.062 | DEBUG    | src.downloader.download:_download:62 - Downloaded c121e3a5e0d3e550b7ff0b4e8d0921f6e9697ef8e91e9197b35b913c633e0ef1.rvp
revanced-builder  | 2024-12-05 10:32:32.062 | INFO     | src.downloader.download:_download:35 - Trying to download 4d98baf8fea2d01a3d0b0a3a03d577a870058e4466d1b1e690cc9a[195]()e3890ff from https://api.revanced.app/v4/patches/list
revanced-builder  | 
4d98baf8fea2d01a3d0b0a3a03d577a870058e4466d1b1e690cc9a195e3890ff: 0.00iB [00:00, ?iB/s]
4d98baf8fea2d01a3d0b0a3a03d577a870058e4466d1b1e690cc9a195e3890ff: 127kiB [00:00, 150MiB/s]
revanced-builder  | 2024-12-05 10:32:32.316 | DEBUG    | src.downloader.download:_download:62 - Downloaded 4d98baf8fea2d01a3d0b0a3a03d577a870058e4466d1b1e690cc9a195e3890ff
revanced-builder  | 2024-12-05 10:32:32.335 | INFO     | src.app:download_apk_for_patching:63 - Downloading apk to be patched by scrapping
revanced-builder  | 2024-12-05 10:32:32.996 | DEBUG    | src.downloader.apkmirror:extract_download_link:40 - Extracting download link from
revanced-builder  | https://www.apkmirror.com/apk/x-corp/twitter/twitter-10-48-0-release-0-release/x-previously-twitter-10-48-0-release-0-android-apk-download/
revanced-builder  | [202]()4-12-05 10:32:34.944 | INFO     | src.downloader.download:_download:35 - Trying to download twitter.apk from https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=6571181&key=a53ba431017dcfa63414894658720dc9603fcd49&forcebaseapk=true

### ENVS

```Dotenv
GLOBAL_CLI_DL=https://github.com/revanced/revanced-cli
GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches
GLOBAL_PATCHES_JSON_DL=https://api.revanced.app/v4/patches/list
TWITTER_ARCHS_TO_BUILD=arm64-v8a
TWITTER_EXCLUDE_PATCH=open-links-with-app-chooser
GLOBAL_SPACE_FORMATTED_PATCHES=true
```

### Additional info

the laest version is 10.70 but it is patching 10.48. why this is happening? i have already excluded that version specific patch. 
![image](https://github.com/user-attachments/assets/6756b069-9a2f-4f32-8b9a-9ce80f7c9200)

**Comment by nikhilbadyal** [comment]
Try adding `TWITTER_VERSION=latest` to envs.

**Comment by ramanveerji** [comment]
> Try adding `TWITTER_VERSION=latest` to envs.

yes it is working. thank you.
