### ISSUE TITLE
Original youtube logo issue

### ISSUE THREAD

**Issue by Lostvale0** [nikhilbadyal/docker-py-revanced#6]
When I built the app on my own it doesn't show me the original youtube logo, it shows me the revanced logo. When I used your apk it has the original youtube logo.
https://github.com/Lostvale0/latest-revanced/releases
![Screenshot_20220830-141234_Package installer](https://user-images.githubusercontent.com/94958746/187392448-59123c39-88d0-458d-bca8-79ee1fe93317.jpg)

**Comment by nikhilbadyal** [comment]
Please skip the branding patch if you want the original logo. 

I'm giving you my own configurations. You can add these in `env`
`EXCLUDE_PATCH_YOUTUBE=custom-branding,enable-debugging`

**Comment by Lostvale0** [comment]
Thank you a lot! Appreciated!
