### ISSUE TITLE
Conflicting with preinstalled YouTube Package

### ISSUE THREAD

**Issue by atiqzawad** [nikhilbadyal/docker-py-revanced#62]
It used to create a revanced app which had an unique icon, name and package name. Recently it is no longer working. Nowadays the Re-youtube apk which is available after running the action is conflicting with my preinstalled YouTube app. I can't uninstall the preinstalled YouTube as it is built into the system. What should I do to change the package name?

**Comment by nikhilbadyal** [comment]
1. Where do you get apps? Install apps that I share or you build those yourself.
2. Share the package name of the currently installed youtube. Use [this](https://play.google.com/store/apps/details?id=com.csdroid.pkg&hl=en_IN&gl=US)
