### ISSUE TITLE
startup failure 

### ISSUE THREAD

**Issue by Pratyay360** [nikhilbadyal/docker-py-revanced#73]
![Screenshot from 2022-11-13 14-06-26](https://user-images.githubusercontent.com/61408566/201514711-dca9b7d4-1063-4f22-a526-dc199abae6c9.png)

**Comment by nikhilbadyal** [comment]
Fixed.

**Comment by Pratyay360** [comment]
> ![image](https://user-images.githubusercontent.com/61408566/201607609-f897a6d3-1775-4b56-a6ea-aa9aa9852bfb.png) job skipping

    if: github.repository == 'nikhilbadyal/docker-py-revanced' in .github/workflows/build-apk.yml   upload-to-telegram-root: is making jobs to skip

**Comment by nikhilbadyal** [comment]
Why would you need both root and non root builds ? 

If you need non root builds get them here. If you need root build go the proper [repo](https://github.com/nikhilbadyal/revanced-magisk-module) to get them.
