### ISSUE TITLE
Patch yt-music arm64-v8a instead of armeabi-v7a.

### ISSUE THREAD

**Issue by bw003** [nikhilbadyal/docker-py-revanced#80]

**Comment by Pratyay360** [comment]
add some details about the problem.

**Comment by Pratyay360** [comment]
`ARCHS_TO_BUILD=arm64-v8a` in the ENVS in the github secret

**Comment by nikhilbadyal** [comment]
> Add `ARCHS_TO_BUILD=arm64-v8a` in the ENVS in the github secret

This issue is something else.
