### ISSUE TITLE
Magisk

### ISSUE THREAD

**Issue by TeaqariaWTF** [nikhilbadyal/docker-py-revanced#95]
Is it possible to create magisk module for YouTube

**Comment by nikhilbadyal** [comment]
[yes](https://github.com/nikhilbadyal/revanced-magisk-module)

**Comment by TeaqariaWTF** [comment]
> yes get it [here](https://github.com/nikhilbadyal/revanced-magisk-module)

yes I know that but I wish it was possible with Docker-py-revanced
