### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TeaqariaWTF** [nikhilbadyal/docker-py-revanced#96]
created files are uploaded to Telegram twice

![Screenshot_20221208-001633_Nagram](https://user-images.githubusercontent.com/90970076/206298186-893782f1-4d77-4930-9f20-2c6433302383.png)
![Screenshot_20221208-001627_Nagram](https://user-images.githubusercontent.com/90970076/206298203-c5d093c4-1f0e-4e4a-964f-236d008f10ac.png)

**Comment by nikhilbadyal** [comment]
Don't look like the case after going through your action runs [here](https://github.com/TeaqariaWTF/RevancedWTF/actions). Try again with [DEBUG](https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/) mode on.

**Comment by TeaqariaWTF** [comment]
PATCH_APPS=youtube,twitter,reddit,twitch,youtube_music,spotify,tiktok,sleep-as-android
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue,materialyou
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music
YOUTUBE_VERSION=17.45.36
YOUTUBE_MUSIC_VERSION=latest
TWITTER_VERSION=latest
REDDIT_VERSION=latest
TIKTOK_VERSION=latest
SPOTIFY_VERSION=latest
TWITCH_VERSION=latest
SLEEP-AS-ANDROID=latest
BUILD_EXTENDED=True

is there an error here?
because sleep as doesn't create android app
@nikhilbadyal

**Comment by nikhilbadyal** [comment]
Sleep as Android is gone. Revanced team removed it. Because of DMCA i guess.

**Comment by TeaqariaWTF** [comment]
my settings are like this but sponsorblock feature is not added
PATCH_APPS=youtube,twitter,reddit,twitch,youtube_music,spotify,tiktok,sleep-as-android
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue,materialyou,sponsorblock
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music
YOUTUBE_VERSION=17.45.36
YOUTUBE_MUSIC_VERSION=latest
TWITTER_VERSION=latest
REDDIT_VERSION=latest
TIKTOK_VERSION=latest
SPOTIFY_VERSION=latest
TWITCH_VERSION=latest
SLEEP-AS-ANDROID=latest
BUILD_EXTENDED=True

**Comment by nikhilbadyal** [comment]
This happening because you add EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue,materialyou,**`sponsorblock`**. Removed **`sponsorblock`** from _EXCLUDE_PATCH_YOUTUBE_EXTENDED_.
It should be

```
PATCH_APPS=youtube,twitter,reddit,twitch,youtube_music,spotify,tiktok,sleep-as-android
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue,materialyou
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music
YOUTUBE_VERSION=17.45.36
YOUTUBE_MUSIC_VERSION=latest
TWITTER_VERSION=latest
REDDIT_VERSION=latest
TIKTOK_VERSION=latest
SPOTIFY_VERSION=latest
TWITCH_VERSION=latest
SLEEP-AS-ANDROID=latest
BUILD_EXTENDED=True
```

**Comment by TeaqariaWTF** [comment]
so the settings should be like this
PATCH_APPS=youtube,twitter,reddit,twitch,youtube_music,spotify,tiktok,sleep-as-android
EXCLUDE_PATCH_YOUTUBE_EXTENDED=custom-branding-red,custom-branding-blue,materialyou
EXCLUDE_PATCH_YOUTUBE_MUSIC_EXTENDED=custom-branding-music
YOUTUBE_VERSION=17.45.36
YOUTUBE_MUSIC_VERSION=latest
TWITTER_VERSION=latest
REDDIT_VERSION=latest
TIKTOK_VERSION=latest
SPOTIFY_VERSION=latest
TWITCH_VERSION=latest
SLEEP-AS-ANDROID=latest
BUILD_EXTENDED=True

**Comment by Pratyay360** [comment]
what does `SLEEP-AS-ANDROID` do just asking out of curiosity.

**Comment by nikhilbadyal** [comment]
> what does `SLEEP-AS-ANDROID` do just asking out of curiosity. 

This [app](https://play.google.com/store/apps/details?id=com.urbandroid.sleep)
